### ISSUE TITLE
How to make it work on LEDE?

### ISSUE THREAD

**Issue by gendouhydeist** [aarond10/https_dns_proxy#1]
Hi! Linux noob here.

I put 'list server = 127.0.0.1:5053' on dnsmasq config and enabled and started https_dns_proxy on init.
But doesn't resolve any dns queries.

Do I have to reroute dns request through IPTables thanks!

**Comment by aarond10** [comment]
Are you sure it's running? 

```
root@OpenWrt:~# ps | grep https_dns_proxy
12345 root     29112 S    /usr/sbin/https_dns_proxy -l 127.0.0.1 -p 5053 -u nobody -g nogroup
30000 root      1176 S    grep https_dns_proxy
```

If you don't see something like that, you may have to enable it at boot (and start it now) as follows:

```
root@OpenWrt:~# /etc/init.d/https_dns_proxy enable
root@OpenWrt:~# ls -l /etc/rc.d | grep https
lrwxrwxrwx    1 root     root            25 Jul  5 19:13 S80https_dns_proxy -> ../init.d/https_dns_proxy
root@OpenWrt:~# /etc/init.d/https_dns_proxy start
```

I'm not sure if quotes in /etc/config/dhcp are important but mine looks like:

`list server '127.0.0.1#5053'`

**Comment by gendouhydeist** [comment]
I'm sure it was on running on daemon.

> list server '127.0.0.1#5053'
probably this why it's not working because I'm using semicolon instead of # sign.

I'll try this later when I got home thanks!

**Comment by gendouhydeist** [comment]
option noresolv '1' "this should be 0"
this cause the dnsmasq not to check localhost queries.

**Comment by gendouhydeist** [comment]
Just want to ask another question, does this encrypt DNS request to able to access block websites?
It doesn't work for me thought.

**Comment by aarond10** [comment]
noresolv '1' is probably what you want if you're planning on forcing all traffic through this. In my case, /etc/resolv/conf only contains "nameserver 127.0.0.1".

All DNS traffic, except for an initial lookup of 'dns.google.com' goes through the proxy. There is a DNS standard called EDNS that can be used to localize DNS traffic. I'm not using it so Google will probably serve you DNS results for your part of the world which may leak a little location. I'll fix that in a new release soon. 

If you're still having trouble, you can try this to get some logs:

```
/etc/init.d/https_dns_proxy stop
https_dns_proxy -g nogroup -v -v -v 
```

This will log to your local terminal without detaching so you can see what the DNS server is doing.

**Comment by gendouhydeist** [comment]
> 
1467845296.366813 main.c:124 System c-ares: 1.11.0
[I] 1467845296.367460 main.c:125 System libcurl: libcurl/7.49.0 mbedTLS/1.3.16
[I] 1467845296.369360 dns_server.c:39 Listening on 127.0.0.1:5053
[D] 1467845296.490189 main.c:107 Received new IP '216.58.208.142'
[D] 1467845301.459730 main.c:83 Received request for 'hitomi.la' id: f6f3, type 1, flags 0100
[D] 1467845301.908829 main.c:83 Received request for 'hitomi.la' id: 2c10, type 1, flags 0100
[D] 1467845302.858262 main.c:63 Received response for id f6f3: {"Status": 0,"TC": false,"RD": true,"RA": true,"AD": true,"CD": false,"Question":[ {"name": "hitomi.la.","type": 1}],"Answer":[ {"name": "hitomi.la.","type": 1,"TTL": 29,"data": "104.23.113.189"},{"name": "hitomi.la.","type": 1,"TTL": 29,"data": "104.23.112.189"}],"Comment": "Response from 173.245.59.130"}
[D] 1467845302.992902 main.c:63 Received response for id 2c10: {"Status": 0,"TC": false,"RD": true,"RA": true,"AD": true,"CD": false,"Question":[ {"name": "hitomi.la.","type": 1}],"Answer":[ {"name": "hitomi.la.","type": 1,"TTL": 29,"data": "104.23.113.189"},{"name": "hitomi.la.","type": 1,"TTL": 29,"data": "104.23.112.189"}],"Comment": "Response from 173.245.58.118"}

**Comment by aarond10** [comment]
CD stands for "Checking disabled". You want this off to ensure DNSSEC responses are validated.
What gives you any suggestion your location is being leaked?
Note that this is only for DNS. If you look up a host with this, then connect directly to it without a VPN, you're IP address will be trivially visible. i.e. It's not a substitute for a VPN. It may be useful *in addition* to a VPN though if privacy is a concern.

**Comment by gendouhydeist** [comment]
Nah, just my speculation. I'll wait for your next release thanks!
