### ISSUE TITLE
Does not compile with Ninja

### ISSUE THREAD

**Issue by neheb** [aarond10/https_dns_proxy#105]
cmake . -G Ninja does not work.

The issue is https://github.com/aarond10/https_dns_proxy/blob/master/CMakeLists.txt#L8 . Basically a quoting bug with CMake.

defining __FILENAME__ in logging.h is probably the correct solution.

**Comment by baranyaib90** [comment]
You are right about the problem, I have fixed it in my fork.
I will contribute the fix sooner or later.
