### ISSUE TITLE
lede doesn't resolve any domain

### ISSUE THREAD

**Issue by cjjdaq** [aarond10/https_dns_proxy#11]
root@LEDE-X64:~# /usr/bin/https_dns_proxy -p 5053 -v -v -v
[I] 1496692158.327939 main.c:135 Built Jun  6 2017 03:19:59.
[I] 1496692158.327961 main.c:136 System c-ares: 1.12.0
[I] 1496692158.327987 main.c:137 System libcurl: libcurl/7.54.0 mbedTLS/2.4.2
[I] 1496692158.328140 dns_server.c:39 Listening on 127.0.0.1:5053
[D] 1496692158.570174 main.c:120 Received new IP '216.58.200.46'
[D] 1496692182.874309 main.c:92 Received request for 'www.youtube.com' id: 6478, type 1, flags 0120
[D] 1496692182.874370 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1496692184.876145 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=www.youtube.com&type=1
[D] 1496692184.876171 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1496692184.876180 https_client.c:137 CURLINFO_HTTP_VERSION: 0
[D] 1496692184.876187 https_client.c:144 CURLINFO_PROTOCOL: 0
[D] 1496692184.876195 https_client.c:165 Times: 0.000041, 0.000000, 0.000000, 0.000000, 0.000000, 2.001638
[D] 1496692184.876215 main.c:57 buflen 0

[D] 1496692187.879817 main.c:92 Received request for 'www.youtube.com' id: 6478, type 1, flags 0120
[D] 1496692187.879864 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1496692189.880417 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=www.youtube.com&type=1
[D] 1496692189.880444 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1496692189.880453 https_client.c:137 CURLINFO_HTTP_VERSION: 0
[D] 1496692189.880460 https_client.c:144 CURLINFO_PROTOCOL: 0
[D] 1496692189.880467 https_client.c:165 Times: 0.000043, 0.000000, 0.000000, 0.000000, 0.000000, 2.000432
[D] 1496692189.880488 main.c:57 buflen 0

**Comment by aarond10** [comment]
I had this same issue and haven't had time to fix it yet.
A few months back the lede distro switched to a libcurl version that dropped HTTP/2 support.
I've had no problems on Ubuntu. Realize that doesn't help much when you want to run it on OpenWRT but a fix here is likely going to require bundling libcurl + nghttp2 with this (bloating it) or directly integrating nghttp2. I haven't had time to look at either. :(

**Comment by cjjdaq** [comment]
I've found the reason because the china great firewall locked dns.google.com

**Comment by aarond10** [comment]
That's a shame. Not a lot I can do about that. :(
There is socks proxy support in the current code that may be useful for you there.

**Comment by crysislinux** [comment]
I meet the same problem. I am in china too.

I run a socks5 proxy on lede and https_dns_proxy  in a virtual ubuntu machine with -t point to the socks5 proxy, and make dnsmasq on lede use https_dns_proxy to resolve the names. everything works. I can ensure that https_dns_proxy get the right address for dns.google.com

but when I run https_dns_proxy on lede, it gets the wrong address for dns.google.com, does not know why
