### ISSUE TITLE
Aborted with "CURLOPT_HTTP_VERSION error 1: Error" when libcurl doens't support HTTP2

### ISSUE THREAD

**Issue by weyou** [aarond10/https_dns_proxy#111]
Found this issue under Openwrt.  The openwrt standard libcurl doens't support HTTP2. 

Before [commit](https://github.com/aarond10/https_dns_proxy/commit/9795480c43a0bcf84f6a60d7532c30ebbf7bbfae),  the code doesn't check the result of the `curl_easy_setopt(ctx->curl, CURLOPT_HTTP_VERSION...)`. The curl will fall back to HTTP1.1 when HTTP2 is unavailable[[1](https://curl.se/libcurl/c/CURLOPT_HTTP_VERSION.html)]. Everything works ok. But after that commit, the process will abort if the result is not `CURLE_OK`.

I suggest to print a warning message to remind user that the HTTP2 is unavailable and continue with the HTTP1.1.

**Comment by baranyaib90** [comment]
Thank you! I will fix it.

**Comment by aarond10** [comment]
Thanks @baranyaib90 for the fix!
