### ISSUE TITLE
https-dns-proxy 2021-05-14 spams log on OpenWrt

### ISSUE THREAD

**Issue by stangri** [aarond10/https_dns_proxy#115]
Hey Aaron, I'm out of my depth with the principal binary, but as reported [here](https://github.com/openwrt/packages/commit/d4f697db7b808aae68e25f3adfc3d23ca432da2e#commitcomment-51488906) the newest version spams the system log on OpenWrt with messages like:

```
04:18:13 https-dns-proxy[13386]: [E] 1622459893.038372 https_client.c:102 CURLOPT_HTTP_VERSION error 1: Error
04:18:13 https-dns-proxy[13386]: [E] 1622459893.038413 https_client.c:104 Try to run application with -x argument!
```

Using `-x` helps, but it's not ideal. Is there something inherently wrong with the OpenWrt's libcurl that the new version can't accept it and has to fallback to HTTP/1? Is this something you can look into relatively quickly or would you recommend I roll back the version of the principal binary to 2021-01-17 which worked well with bundled libcurl?

**Comment by baranyaib90** [comment]
I could change the code to print it only at first occurrence and in runtime force set the -x option.
That would fix the log flood and the proper libcurl API usage.

**Comment by stangri** [comment]
I've pushed the fix to the init script to force HTTP/1 fallback for the newer version. I'm wondering why has it started happening with this version and  if something in the code of the binary or dependencies can be adjusted to make it work properly without HTTP/1 fallback.

**Comment by baranyaib90** [comment]
This log flood is the side effect of the fix for #111 
My new pull request (#116) will fix this flooding issue by forcing the option -x in runtime.

**Comment by stangri** [comment]
So it's a libcurl in OpenWrt which needs to be updated to support HTTP/2?

**Comment by baranyaib90** [comment]
As far I know, in OpenWRT by default the HTTP/2 support of libcurl is disabled.
And it could be enabled in manual build with "make menuconfig".

**Comment by stangri** [comment]
Thank you, confirmed working with your PR.
