### ISSUE TITLE
does openwrt/lede version support proxy?

### ISSUE THREAD

**Issue by crysislinux** [aarond10/https_dns_proxy#12]
Thanks for the amazing app. 

It seems that it does not support proxy on lede. Following is the init script for https_dns_proxy which comes from lede's package  (opkg install https_dns_proxy).

I tried to start https_dns_proxy with -t param, but seems no lucky.

```bash
root@LEDE:~# cat /etc/init.d/https_dns_proxy
#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/sbin/https_dns_proxy

start_instance() {
	local cfg="$1"
	local listen_addr listen_port user group

	config_get listen_addr "$cfg" listen_addr
	config_get listen_port "$cfg" listen_port
	config_get user "$cfg" user
	config_get group "$cfg" group

	procd_open_instance
	procd_set_param command ${PROG} \
		-a "$listen_addr" -p "$listen_port" \
		-u "$user" -g "$group"
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "https_dns_proxy"
}

start_service() {
	config_load 'https_dns_proxy'
	config_foreach start_instance 'https_dns_proxy'
}
```

I cannot get https_dns_proxy work on lede. I saw an open issue about openwrt/lede, but am not sure whether it's the same problem since I am in China, where may have the most complex network in the world...

Currently I am doing the following thing to make it work as a workaround.

Network 
lede router --> notebook  --> ubuntu in virtualbox with bridge network
192.168.1.1   ----  192.168.1.2 ----- 192.168.1.3

there is a socks5 proxy on lede,  socks5://192.168.1.1:1080

a https_dns_proxy instance is running on ubuntu with  -t socks5://192.168.1.1:1080

dnsmasq.conf     
server=/#/192.168.1.3#5053

The workaround works but it's annoying because when the notebook get sleep. https_dns_proxy also stop working. thus other devices cannot resolve name anymore.

Hope we can  figure out what's the problem.  Thanks

**Comment by crysislinux** [comment]
I can ensure that https_dns_proxy get the right ip for dns.google.com

```
root@LEDE:~/packages# https_dns_proxy -a 0.0.0.0  -t socks5://192.168.1.1:1080 -b 127.0.0.1 -v -v -v
[I] 1500602785.128632 main.c:132 System c-ares: 1.11.0
[I] 1500602785.129354 main.c:133 System libcurl: libcurl/7.52.1 mbedTLS/2.5.1
[I] 1500602785.131925 dns_server.c:39 Listening on 0.0.0.0:5053
[D] 1500602785.386550 main.c:117 Received new IP '74.125.200.139'
[D] 1500602850.355974 main.c:92 Received request for 'facebook.com' id: bce1, type 1, flags 0100
[D] 1500602850.362499 main.c:57 buflen 0

[D] 1500602855.358398 main.c:92 Received request for 'facebook.com' id: bce1, type 1, flags 0100
[D] 1500602855.364331 main.c:57 buflen 0

[D] 1500602860.363665 main.c:92 Received request for 'facebook.com' id: bce1, type 1, flags 0100
[D] 1500602860.369897 main.c:57 buflen 0
```

On ubuntu version, I can see something like this
```
https_client.c:72 Using curl proxy: socks5://192.168.1.1:1080
```

**Comment by aarond10** [comment]
Last I checked, lede had a broken libcurl that is missing http/2 support.
What's worse, it's not reporting errors, just returning empty payloads.

**Comment by daztucker** [comment]
See my longer comment in issue #9 but the short version is that the empty payloads are due to a known problem in libcurl <7.53.0 with mbedtls and nonblocking IO (https://github.com/curl/curl/commit/b993d2cca536870ecdf3b4611de9f77215af8eb8).

**Comment by daztucker** [comment]
Submitted https://github.com/lede-project/source/pull/1627 to get LEDE's stable libcurl fixed (HEAD is based on a version that already has the fix).

**Comment by crysislinux** [comment]
@daztucker It's great to see a solution. Your pr was closed, they were merging lede back to openwrt, so you need to make the pr to openwrt.

**Comment by daztucker** [comment]
https://github.com/openwrt/openwrt/pull/674

**Comment by daztucker** [comment]
OpenWRT pull request against the lede-17.01 branch has been merged so if you update to libcurl_7.52.1-7 you should see https_dns_proxy start to be able to resolve addresses.

Note that you will also need to install the ca-bundle package to get the required SSL certificates, otherwise it'll continue to fail with the same symptoms...

**Comment by daztucker** [comment]
https://github.com/openwrt/packages/pull/5497 and https://github.com/openwrt/packages/pull/5499 to update the https_dns_package to pick up the code fixes and add a dependency on ca-bundle.

**Comment by daztucker** [comment]
Going back to the original question of proxy support, -t's usage says: "Initial DNS resolution can't be done over this."

If using SOCKS4a (https://www.openssh.com/txt/socks4a.protocol) or SOCKS5 (https://tools.ietf.org/html/rfc1928) then it is possible to get the SOCKS server to resolve the address for the client.  I'm not sure how hard this would be to implement, though.

**Comment by daztucker** [comment]
https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html has the following proxy types:
socks4a:// - SOCKS4a Proxy. Proxy resolves URL hostname.
socks5h:// - SOCKS5 Proxy. Proxy resolves URL hostname.

When using those (and http/https for that matter) https_dns_proxy should probably not try to resolve dns.google.com itself.  The proxy may be some distance away and having the proxy resolve the name might get an IP address much closer to the proxy and thus faster.

**Comment by crysislinux** [comment]
@daztucker thank you very much, will have a try this weekend.

**Comment by aarond10** [comment]
@crysislinux, if this works, please let us know and I'll close this issue.

**Comment by crysislinux** [comment]
@aarond10 thank you. it basically works in lede now, the proxy_server is missing in the init script and config file, but I can handle that myself.

The problem is that when the proxy_server(socks5h://127.0.0.1:1080) is not ready when http_dns_proxy starts(I am not 100% sure this is the problem, but I tried several times, whenever enable proxy_server, the problem happens), http_dns_proxy will keep eating a lot of cpu time(around 70  - 90%), after restart http_dns_proxy, the cpu cost becomes normal. Not sure what's wrong here, I guess it's doing some work infinitely. Maybe we need some kind of timeout and connection test guard mechanism(just drop the request if the proxy is not ready or it becomes too slow) to avoid such problem.

Currently I made another init script which will simply sleep a while and then start http_dns_proxy to workaround the problem.

**Comment by crysislinux** [comment]
Sorry, just tried more times. my workaround does not work, it's still using a lot of cpu on start when proxy_server is enabled

**Comment by daztucker** [comment]
You're using a local SOCKS proxy running on the same machine as https_dns_proxy?  You could try changing the start order so that the SOCKS server starts before https_dns_proxy (which current starts at 80):
 
$ ls -l /etc/rc.d/*https_dns_proxy
lrwxrwxrwx    1 root     root            25 Jan 27 13:55 /etc/rc.d/S80https_dns_proxy -> ../init.d/https_dns_proxy

https_dns_proxy should be able to recover from this state, though.

**Comment by daztucker** [comment]
Oh, does your SOCKS server do DNS lookups?  If you have a circular dependency like that, and if the SOCKS server does DNS lookups on, say. incoming clients, I could totally imagine it spinning as you describe until you manually break the loop by restarting it.

**Comment by crysislinux** [comment]
> You're using a local SOCKS proxy running on the same machine as https_dns_proxy?

yes

> You could try changing the start order so that the SOCKS server starts before https_dns_proxy

I tried to make another start script which starts at 99, the script starts https_dns_proxy after sleep 10, but still no lucky

> Oh, does your SOCKS server do DNS lookups?

not very sure about that, it's a socks5 proxy server.

> If you have a circular dependency like that

not quick sure what circular dependency is here. a local program connect to a remote server with  ip, and then create a local socks5 proxy server(this is what used by https_dns_proxy). I think the proxy server itself don't need to lookup for that.

I will try to make https_dns_proxy log something to see what happened

**Comment by daztucker** [comment]
You could also try stracing the SOCKS server to a log and seeing if it's sending anything to port 53 (eg, add "strace -f -e trace=network -o /tmp/socks.trace " to the line starting the SOCKS server binary then grep it for 53).

**Comment by aarond10** [comment]
@crysislinux, is this still an issue for you?

**Comment by crysislinux** [comment]
@aarond10 I think we can close this one since it already goes beyond the scope of the title, and it does support proxy on LEDE. I haven't found the reason for the cpu usage problem, but I am using another DNS lookup proxy now.
