### ISSUE TITLE
could you add HE?

### ISSUE THREAD

**Issue by systemcrash** [aarond10/https_dns_proxy#127]
Please :)

https://ordns.he.net
https://forums.he.net/index.php?topic=3996.0
https://bgp.he.net/dns/ordns.he.net#_dns

**Comment by baranyaib90** [comment]
I do not know what do you mean by adding it... It' supported and that's all.
It is possible for the users to use it if they choose to: `./https_dns_proxy -r https://ordns.he.net/ ...`
Both HTTP 1.1 and 2.0 works.
If you want to advertise the service, try here: https://en.wikipedia.org/wiki/Public_recursive_name_server

**Comment by systemcrash** [comment]
OK, thank you.
