### ISSUE TITLE
Cross-compile binaries for ARM v7 and ARM 64

### ISSUE THREAD

**Issue by CensorKao** [aarond10/https_dns_proxy#129]
I was just looking into doing this (and sorry this took so long)! I'm pretty unfamiliar with the arm64/armv7 ecosystem. Is the ask to just publish in our release, or to publish to a package manager?

**Comment by baranyaib90** [comment]
For now only OpenWRT and archlinux pakage and Docker container is provided.
If you want it on custom ARM system, you should compile it for yourself.
It work on Raspberry PI 4 Raspbian (ARM v8) pretty easily.

**Comment by aarond10** [comment]
+1. I only run an OpenWRT MIPS build but the build process is a cross compile. e.g. An example Cortex A72 cross-compile package is here: https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a72/packages/https-dns-proxy_2021-11-22-2_aarch64_cortex-a72.ipk
