### ISSUE TITLE
Does not support http 1.1?

### ISSUE THREAD

**Issue by wykeinstein** [aarond10/https_dns_proxy#142]
There is a false word after the -x option in the help output, does that mean that the default https-dns-proxy does not support http 1.1?

**Comment by wykeinstein** [comment]
Can someone answer?

**Comment by baranyaib90** [comment]
false means, that it's not used by default.
The proxy uses HTTP/2.0 by default, and with -x/-q you can choose to use HTTP 1.1/3
You can check the used protocol version with using "-v -v -v" verbose debugging options.
