### ISSUE TITLE
To use HTTP/3

### ISSUE THREAD

**Issue by hadzhioglu** [aarond10/https_dns_proxy#143]
I can't use HTTP/3, although I compile everything correctly, I use the Padavan firmware.
I run in the router in Run after the WAN up / down event:

```
### Run DNS-over-HTTPS (DoH) proxy
WAN_STATE=$1
WAN_IF=$2

wan_up() {
WAN_IP=`nvram get wan0_ipaddr`
logger "WAN $WAN_IF ($WAN_IP) is UP."
doh_proxy -r "https://blitz.ahadns.com/1:4" -d -4 -a 127.0.0.1 -p 65054 -b 1.1.1.2,8.8.8.8,9.9.9.9 -q -v
logger -t doh_proxy "Start resolving to blitz.ahadns.com"
doh_proxy2 -r "https://basic.rethinkdns.com/1:AAQCAA==" -d -4 -a 127.0.0.1 -p 65055 -b 1.1.1.2,8.8.8.8,9.9.9.9 -q -v
logger -t doh_proxy2 "Start resolving to basic.rethinkdns.com"
}

wan_down() {
killall -SIGHUP doh_proxy
killall -SIGHUP doh_proxy2
logger -t doh_proxy "Shutdown"
}

case "$WAN_STATE" in
up)
wan_up
;;
down)
wan_down
;;
esac

```

**Comment by baranyaib90** [comment]
First check with cloudflare (https://cloudflare-dns.com/dns-query) if the proxy (you compiled) works successfuly with HTTP/3.
If it does, maybe blitz.ahadns.com and/or basic.rethinkdns.com does not support HTTP/3.
I suggest to use "-v -v -v" for debugging purpose.

**Comment by ignoramous** [comment]
Hi there,

rdns co-developer here.

The `basic` RethinkDNS resolver should (does) support h3; test: [http3check.net](https://www.http3check.net/?host=https%3A%2F%2Fbasic.rethinkdns.com%2F).

Or:

```
curl --http3 -k -H 'accept: application/dns-message' 'basic.rethinkdns.com/?dns=AAABAAABAAAAAAAAA2NkbgdzZWdtZW50A2NvbQAAAQAB' -vv --output /dev/null 
```

**Comment by ignoramous** [comment]
Oh yeah, quite possibly QUIC is censored, or some middleware / firewall drops QUIC / drops UDP (which QUIC uses) altogether.

See also: https://github.com/kelmenhorst/quic-censorship
