### ISSUE TITLE
This is an awesome app - how to add manual dns records?

### ISSUE THREAD

**Issue by haowang1018** [aarond10/https_dns_proxy#145]
Hi,

I installed the https_dns_proxy as a DNS server for other Linux hosts (to solve name over http proxy), since there are some internal host names cannot be resolved by the http proxy server, how can I add some manual DNS records (instead of query to http proxy server)?

Below is the example of the environment
host 1 - 192.168.0.100, installed https_dns_proxy as DNS server, and provide DNS service at UDP 53
host 2 - 192.168.0.101, configured DNS server as 192.168.0.100 

Thanks !

**Comment by aarond10** [comment]
You can't do that with https_dns_proxy directly. Generally what you would
do is connect it to Dnsmasq and use that to customize the responses.

Something like: HTTPS DNS Service <-- https_dns_proxy <-- dnsmasq <--
clients.

The https_dns_proxy is just a protocol translator from HTTPS to UDP DNS

**Comment by haowang1018** [comment]
> 
Many thanks for your quick response, it works!!!

Just share my setup
- Install https_dns_proxy (via docker), and mapping DNS port to 5053
- Install dnsmasp, and configure server=127.0.0.1#5053
