### ISSUE TITLE
Any plans to support ECH?

### ISSUE THREAD

**Issue by usr97629238** [aarond10/https_dns_proxy#156]
https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-16

If DoH is enabled in the browser, it connects using ECH just fine (https://tls-ech.dev/ or https://defo.ie/ech-check.php), but using the OpenWrt's https_dns_proxy it does not.
And I'm not sure about the exact cause of it not working, it could be that https_dns_proxy is not requesting/forwarding the necessary records or it could be that the browser is not trying to establish a ECH connection, thinking that it's using plaintext DNS.

**Comment by aarond10** [comment]
Hmm. Interesting question.
libcurl handles the TLS/SSL side of things for us and ECH support seems
lacking.
There seem to have been two attempts to add it  (e.g.
https://github.com/curl/curl/pull/4011) but it doesn't look like it has
landed.

**Comment by usr97629238** [comment]
But should dns proxy even touch the encryption part? In my layman understanding dns proxy should just pass the "_required by ECH dns records_" (not quite sure about this) that would allow the browser or, in that case, curl to establish the ECH connection with the target server.

**Comment by aarond10** [comment]
I might be misunderstanding. (I haven't tried ECH but may have a look on
the weekend if I have some time.)
Is the issue is that:
  a. the proxy's connection to its HTTPS DNS server is not protected via
ECH; or
  b. the proxy is not passing on ECH DNS (RR) records for some reason?

I assumed (a) because (b) should be transparently passed through -- the
proxy doesn't do any transcoding of records anymore.
If (b), then possibly there might be an issue with large record sizes
affecting this?

**Comment by aarond10** [comment]
If (a), the problem is that libcurl doesn't support ECH yet. I believe
WolfSSL does, but changing openwrt libcurl to use that might be a can of
worms.

**Comment by usr97629238** [comment]
My understanding is very vague, should spend some time reading through those RFCs, if only they would have written it all clearly in one document, without a trillion references to other RFCs, but I believe it's either:
 b. the proxy is not passing on ECH DNS (RR) records for some reason?
or even
 c. the browser is not trying to establish a ECH connection, thinking that it's using plaintext DNS

And for (c) the possible mitigation would be for the DNS proxy to provide its services through both cleartext DNS - for ECH unaware devices/apps and through DoH for ECH aware devices/apps.

**Comment by usr97629238** [comment]
It must be (c) the browser is not trying to establish a ECH connection, thinking that it's using plaintext DNS, cause with the last (114) version of this Chromium fork https://gitlab.com/divested-mobile/mulch on the phone it connects fine.
Not so much luck on the desktop Edge though.

Here are some more links to check:
https://crypto.cloudflare.com/cdn-cgi/trace (should say sni=encrypted)
https://defo.ie/
https://www.cloudflare.com/ssl/encrypted-sni/

**Comment by usr97629238** [comment]
Some followup from here https://defo.ie/:
There is talk about key rotation _"Short term keys are usable for three hours, but only published for two hours, after which they are no longer published but are still usable for the third hour. A new short term key is generated hourly, so we publish 2 short term keys at any given moment"_, **so how that works with the caching, that is done by https_dns_proxy?**
And indeed that confirms (c): _"Chromium (version 105+) now also supports ECH, but again behind a flag and you **also need DoH turned on**"_
