### ISSUE TITLE
setting version information while building

### ISSUE THREAD

**Issue by stangri** [aarond10/https_dns_proxy#157]
@aarond10 so with https://github.com/aarond10/https_dns_proxy/commit/d03e11572562f008f68df217a7378628f1bb7b79 can I somehow set the https_dns_proxy binary to report custom version information or did I misread the intention of the commit?

**Comment by aarond10** [comment]
Sorry, I should have rebased on top of this
<https://github.com/aarond10/https_dns_proxy/commit/58bdca9743bb6447cd9d837ff984ce32059bf288>
first
which is now mixed in with my cast
<https://github.com/aarond10/https_dns_proxy/commit/a5c4428ef963a74b8a142a6f9f3a77cf6ee0bdc5>
change in that commit.
The version change was to set a reasonable default (currently
"2023.01.01-atLeast") if GIT_VERSION is missing.
If OpenWRT relies on this, I can bump it now.

**Comment by stangri** [comment]
No worries, I can create a patch for OpenWrt which will substitute it with the version I want printed from the binary.

**Comment by stangri** [comment]
Thanks, I'll have the version set thru patching src/options.c instead of CMakeLists file like before: https://github.com/openwrt/packages/pull/21177
