### ISSUE TITLE
add linux/arm/v7 build

### ISSUE THREAD

**Issue by ethaniel** [aarond10/https_dns_proxy#159]
Hello! 

Can you make a build for linux/arm/v7 please?
A lot of us use pihole on raspberries, and having your proxy would be an amazing addition.

**Comment by aarond10** [comment]
I am not publishing binary releases here, but the source code should build just fine on ARM. It runs on OpenWRT which includes x86, MIPS, Arm, ... Perhaps someone from pihole could act as a maintainer for a build?
