### ISSUE TITLE
Bootstrap the bootstrap

### ISSUE THREAD

**Issue by orent** [aarond10/https_dns_proxy#16]
Suggestion: call ares_set_servers to use 8.8.8.8 and 8.8.4.4 for resolving dns.google.com

This should eliminate dependencies on any local or dhcp (mis)configuration.

**Comment by wheelerlaw** [comment]
If global DNS isn't available to `https_dns_proxy` at startup, won't this be a problem?

**Comment by aarond10** [comment]
This already happens [here](https://github.com/aarond10/https_dns_proxy/blob/master/src/dns_poller.c#L57
). The default is 8.8.8.8 and can be controlled via command-line flag.

If the resolution fails, DNS requests will fail until it succeeds. The dns_poller will periodically re-resolve dns.google.com via ares in case the mapping changes (per minute IIRC, you can check yourself in the code).

**Comment by aarond10** [comment]
Every [120 seconds](https://github.com/aarond10/https_dns_proxy/blob/master/src/main.c#L186).
