### ISSUE TITLE
Hostname is not resolved if it contains a port at the end

### ISSUE THREAD

**Issue by jzbor** [aarond10/https_dns_proxy#160]
[`hostname_from_uri`](https://github.com/aarond10/https_dns_proxy/blob/d03e11572562f008f68df217a7378628f1bb7b79/src/main.c#L43) fails if the address is a hostname (that should be resolved) followed by a port.

**Comment by baranyaib90** [comment]
Issue is valid, will be fixed soon.
[I] 1700258517.310551 main.c:312 Resolver prefix 'https://one.one.one.one:433/dns-query' doesn't appear to contain a hostname. DNS polling disabled.
