### ISSUE TITLE
Can not resolve url due to multiple Trying 8.8.8.8:443...

### ISSUE THREAD

**Issue by hungthele** [aarond10/https_dns_proxy#169]
I am having issues with the https client multiple Trying to connect to 8.8.8.8:443...
May be the reason is **Didn't find Session ID in cache for host HTTPS://dns.google:443**
I'm not sure the root cause.
Log output below.

Any ideas? Please help me to find out the reason

[I] 1709005584.821880 main.c:218 Version: 2023.11.20-489c57e
[I] 1709005584.822048 main.c:219 Built: Feb 26 2024 04:50:59
[I] 1709005584.823269 main.c:220 System c-ares: 1.16.0
[I] 1709005584.824088 main.c:221 System libcurl: libcurl/7.87.0 OpenSSL/1.1.1q zlib/1.2.13 libidn2/2.3.0
[W] 1709005584.859026 main.c:230 HTTP/2 is not supported by current libcurl
[W] 1709005584.859063 main.c:235 HTTP/3 is not supported by current libcurl
[I] 1709005584.872489 dns_server.c:57 Listening on 127.0.0.1:2023
[D] 1709005584.872571 logging.c:41 starting periodic log flush timer
[D] 1709005584.886183 dns_poller.c:180 Nameservers count: 2
[I] 1709005584.886198 main.c:308 DNS polling initialized for 'dns.google'
[D] 1709005584.886279 dns_poller.c:114 Starting DNS query
[D] 1709005584.889900 dns_poller.c:41 Reserved new io event: 0x55968c1290
[D] 1709005584.890754 dns_poller.c:126 DNS poll interval changed to: 0.699
[D] 1709005585.263421 main.c:184 Received new DNS server IP '8.8.8.8,8.8.4.4'
[D] 1709005585.282394 dns_poller.c:88 DNS poll interval changed to: 120
[D] 1709005585.282427 dns_poller.c:31 Released used io event: 0x55968c1290
[D] 1709005655.494709 main.c:112 Received request for id: 81E, len: 28
[D] 1709005655.497096 https_client.c:253 081E: Requesting HTTP/1.1
[D] 1709005655.514958 https_client.c:207 081E: * Added dns.google:443:8.8.8.8,8.8.4.4 to DNS cache
[D] 1709005655.516712 https_client.c:207 081E: * STATE: INIT => CONNECT handle 0x55968d6ab0; line 1909 (connection #-5000)
[D] 1709005655.523864 https_client.c:207 081E: * Added connection 0. The cache now contains 1 members
[D] 1709005655.523887 https_client.c:207 081E: * Hostname dns.google was found in DNS cache
[D] 1709005655.523893 https_client.c:207 081E: * [CONN-0-0] setup, init filter chain
[D] 1709005655.523898 https_client.c:207 081E: * [CONN-0-0] cf_add(filter=SOCKET)
[D] 1709005655.523904 https_client.c:207 081E: * [CONN-0-0] cf_add(filter=SSL)
[D] 1709005655.523908 https_client.c:207 081E: * [CONN-0-0][CF-SOCKET] setup(remotehost=dns.google)
[D] 1709005655.523914 https_client.c:207 081E: * STATE: CONNECT => CONNECTING handle 0x55968d6ab0; line 1965 (connection #0)
[D] 1709005655.523922 https_client.c:207 081E: * family0 == v4, family1 == v6
[D] 1709005655.523984 https_client.c:79 curl opened socket: 9
[D] 1709005655.524007 https_client.c:207 081E: *   Trying 8.8.8.8:443...
[D] 1709005655.524345 https_client.c:207 081E: * [CONN-0-0] connect(block=0)-> 0, done=0
[D] 1709005655.725167 https_client.c:207 081E: * [CONN-0-0] connect(block=0)-> 0, done=0
[D] 1709005660.524048 https_client.c:207 081E: * Connected to dns.google (8.8.8.8) port 443 (#0)
[D] 1709005660.528883 https_client.c:207 081E: * ALPN: offers http/1.1
[D] 1709005660.559480 https_client.c:207 081E: *  CAfile: /etc/ssl/certs/ca-certificates.crt
[D] 1709005660.559495 https_client.c:207 081E: *  CApath: none
[D] 1709005660.568043 https_client.c:207 081E: * [CONN-0] Didn't find Session ID in cache for host HTTPS://dns.google:443
[D] 1709005660.666245 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
[D] 1709005660.668212 https_client.c:207 081E: * [CONN-0-0] connect(block=0)-> 0, done=0
[D] 1709005660.668374 https_client.c:603 Reserved new io event: 0x7fc3d15f20
[D] 1709005660.946419 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
[D] 1709005660.958121 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
[D] 1709005660.958242 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Certificate (11):
[D] 1709005660.985094 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, CERT verify (15):
[D] 1709005661.021271 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Finished (20):
[D] 1709005661.021383 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
[D] 1709005661.021481 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Finished (20):
[D] 1709005661.021729 https_client.c:207 081E: * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
[D] 1709005661.021737 https_client.c:207 081E: * ALPN: server accepted http/1.1
[D] 1709005661.022275 https_client.c:207 081E: * Server certificate:
[D] 1709005661.022297 https_client.c:207 081E: *  subject: CN=dns.google
[D] 1709005661.022313 https_client.c:207 081E: *  start date: Feb  5 08:19:57 2024 GMT
[D] 1709005661.022320 https_client.c:207 081E: *  expire date: Apr 29 08:19:56 2024 GMT
[D] 1709005661.022369 https_client.c:207 081E: *  subjectAltName: host "dns.google" matched cert's "dns.google"
[D] 1709005661.022392 https_client.c:207 081E: *  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
[D] 1709005661.022396 https_client.c:207 081E: *  SSL certificate verify ok.
[D] 1709005661.022405 https_client.c:207 081E: * [CONN-0-0] connect(block=0)-> 0, done=1
[D] 1709005661.022411 https_client.c:207 081E: * STATE: CONNECTING => PROTOCONNECT handle 0x55968d6ab0; line 2073 (connection #0)
[D] 1709005661.022418 https_client.c:207 081E: * [CONN-0-0] connect(block=0)-> 0, done=1
[D] 1709005661.022423 https_client.c:207 081E: * STATE: PROTOCONNECT => DO handle 0x55968d6ab0; line 2103 (connection #0)
[D] 1709005661.025888 https_client.c:207 081E: > POST /dns-query HTTP/1.1
[D] 1709005661.025899 https_client.c:207 081E: > Host: dns.google
[D] 1709005661.025901 https_client.c:207 081E: > User-Agent: https_dns_proxy/0.3
[D] 1709005661.025903 https_client.c:207 081E: > Accept: application/dns-message
[D] 1709005661.025905 https_client.c:207 081E: > Content-Type: application/dns-message
[D] 1709005661.025907 https_client.c:207 081E: > Content-Length: 28
[D] 1709005661.027145 https_client.c:207 081E: * STATE: DO => DID handle 0x55968d6ab0; line 2199 (connection #0)
[D] 1709005661.027159 https_client.c:207 081E: * STATE: DID => PERFORMING handle 0x55968d6ab0; line 2318 (connection #0)
[D] 1709005661.028028 https_client.c:207 081E: * readwrite_data(handle=0x55968d6ab0) -> 0
[D] 1709005661.028037 https_client.c:207 081E: * Curl_readwrite(handle=0x55968d6ab0) -> 0
[D] 1709005661.306142 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
[D] 1709005661.306229 https_client.c:207 081E: * [CONN-0] Didn't find Session ID in cache for host HTTPS://dns.google:443
[D] 1709005661.306240 https_client.c:207 081E: * [CONN-0] Added Session ID to cache for HTTPS://dns.google:443 [server]
[D] 1709005661.306315 https_client.c:207 081E: * [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
[D] 1709005661.306631 https_client.c:207 081E: * [CONN-0] Found Session ID in cache for host HTTPS://dns.google:443
[D] 1709005661.306639 https_client.c:207 081E: * old SSL session ID is stale, removing
[D] 1709005661.306788 https_client.c:207 081E: * [CONN-0] Added Session ID to cache for HTTPS://dns.google:443 [server]
[D] 1709005661.309435 https_client.c:207 081E: * Mark bundle as not supporting multiuse
[D] 1709005661.309449 https_client.c:207 081E: * HTTP 1.1 or later with persistent connection
[D] 1709005661.309457 https_client.c:207 081E: < HTTP/1.1 200 OK
[D] 1709005661.309466 https_client.c:207 081E: < X-Content-Type-Options: nosniff
[D] 1709005661.309476 https_client.c:207 081E: < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[D] 1709005661.309479 https_client.c:207 081E: < Date: Tue, 27 Feb 2024 03:47:44 GMT
[D] 1709005661.309484 https_client.c:207 081E: < Cache-Control: private, max-age=0
[D] 1709005661.309490 https_client.c:207 081E: < Content-Type: application/dns-message
[D] 1709005661.309492 https_client.c:207 081E: < Server: HTTP server (unknown)
[D] 1709005661.309497 https_client.c:207 081E: < Content-Length: 28
[D] 1709005661.309500 https_client.c:207 081E: < X-XSS-Protection: 0
[D] 1709005661.309503 https_client.c:207 081E: < X-Frame-Options: SAMEORIGIN
[D] 1709005661.309507 https_client.c:207 081E: < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
[D] 1709005661.309537 https_client.c:207 081E: * readwrite_data(handle=0x55968d6ab0) -> 0
[D] 1709005661.309544 https_client.c:207 081E: * Curl_readwrite(handle=0x55968d6ab0) -> 0
[D] 1709005661.309551 https_client.c:207 081E: * STATE: PERFORMING => DONE handle 0x55968d6ab0; line 2517 (connection #0)
[D] 1709005661.309557 https_client.c:207 081E: * multi_done: status: 0 prem: 0 done: 0
[D] 1709005661.310675 https_client.c:207 081E: * Connection #0 to host dns.google left intact
[D] 1709005661.310711 https_client.c:593 Released used io event: 0x7fc3d15f20
[D] 1709005661.310725 https_client.c:346 081E: curl request succeeded
[D] 1709005661.310734 https_client.c:439 081E: CURLINFO_NUM_CONNECTS: 1
[D] 1709005661.310736 https_client.c:451 081E: CURLINFO_EFFECTIVE_URL: https://dns.google/dns-query
[D] 1709005661.310739 https_client.c:458 081E: CURLINFO_HTTP_VERSION: 1.1
[D] 1709005661.310743 https_client.c:488 081E: Times: 0.007144, 5.007261, 10.512917, 5.510407, 5.790145, 5.793423
[D] 1709005661.310762 main.c:83 Received response for id: 81E, len: 28
[D] 1709005661.319878 main.c:112 Received request for id: 6C7E, len: 28
[D] 1709005661.319899 https_client.c:253 6C7E: Requesting HTTP/1.1
[D] 1709005661.320008 https_client.c:207 6C7E: * RESOLVE dns.google:443 is - old addresses discarded
[D] 1709005661.320153 https_client.c:207 6C7E: * Added dns.google:443:8.8.8.8,8.8.4.4 to DNS cache
[D] 1709005661.320169 https_client.c:207 6C7E: * STATE: INIT => CONNECT handle 0x55969a6fb0; line 1909 (connection #-5000)
[D] 1709005661.320243 https_client.c:207 6C7E: * Found bundle for host: 0x55968c1340 [serially]
[D] 1709005661.320280 https_client.c:207 6C7E: * Re-using existing connection #0 with host dns.google
[D] 1709005661.320288 https_client.c:207 6C7E: * STATE: CONNECT => CONNECTING handle 0x55969a6fb0; line 1965 (connection #0)
[D] 1709005661.320294 https_client.c:207 6C7E: * [CONN-0-0] connect(block=0)-> 0, done=1
[D] 1709005661.320299 https_client.c:207 6C7E: * STATE: CONNECTING => PROTOCONNECT handle 0x55969a6fb0; line 2073 (connection #0)
[D] 1709005661.320304 https_client.c:207 6C7E: * STATE: PROTOCONNECT => DO handle 0x55969a6fb0; line 2092 (connection #0)
[D] 1709005661.320584 https_client.c:207 6C7E: > POST /dns-query HTTP/1.1
[D] 1709005661.320588 https_client.c:207 6C7E: > Host: dns.google
[D] 1709005661.320590 https_client.c:207 6C7E: > User-Agent: https_dns_proxy/0.3
[D] 1709005661.320592 https_client.c:207 6C7E: > Accept: application/dns-message
[D] 1709005661.320594 https_client.c:207 6C7E: > Content-Type: application/dns-message
[D] 1709005661.320596 https_client.c:207 6C7E: > Content-Length: 28
[D] 1709005661.320607 https_client.c:207 6C7E: * STATE: DO => DID handle 0x55969a6fb0; line 2199 (connection #0)
[D] 1709005661.320614 https_client.c:207 6C7E: * STATE: DID => PERFORMING handle 0x55969a6fb0; line 2318 (connection #0)
[D] 1709005661.320629 https_client.c:207 6C7E: * Curl_readwrite(handle=0x55969a6fb0) -> 0
[D] 1709005661.320645 https_client.c:603 Reserved new io event: 0x7fc3d15f20
[D] 1709005661.587290 https_client.c:207 6C7E: * Mark bundle as not supporting multiuse
[D] 1709005661.587304 https_client.c:207 6C7E: * HTTP 1.1 or later with persistent connection
[D] 1709005661.587309 https_client.c:207 6C7E: < HTTP/1.1 200 OK
[D] 1709005661.587315 https_client.c:207 6C7E: < X-Content-Type-Options: nosniff
[D] 1709005661.587323 https_client.c:207 6C7E: < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[D] 1709005661.587327 https_client.c:207 6C7E: < Date: Tue, 27 Feb 2024 03:47:44 GMT
[D] 1709005661.587332 https_client.c:207 6C7E: < Cache-Control: private, max-age=0
[D] 1709005661.587336 https_client.c:207 6C7E: < Content-Type: application/dns-message
[D] 1709005661.587339 https_client.c:207 6C7E: < Server: HTTP server (unknown)
[D] 1709005661.587344 https_client.c:207 6C7E: < Content-Length: 28
[D] 1709005661.587347 https_client.c:207 6C7E: < X-XSS-Protection: 0
[D] 1709005661.587350 https_client.c:207 6C7E: < X-Frame-Options: SAMEORIGIN
[D] 1709005661.587353 https_client.c:207 6C7E: < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
[D] 1709005661.587377 https_client.c:207 6C7E: * readwrite_data(handle=0x55969a6fb0) -> 0
[D] 1709005661.587384 https_client.c:207 6C7E: * Curl_readwrite(handle=0x55969a6fb0) -> 0
[D] 1709005661.587391 https_client.c:207 6C7E: * STATE: PERFORMING => DONE handle 0x55969a6fb0; line 2517 (connection #0)
[D] 1709005661.587396 https_client.c:207 6C7E: * multi_done: status: 0 prem: 0 done: 0
[D] 1709005661.587479 https_client.c:207 6C7E: * Connection #0 to host dns.google left intact
[D] 1709005661.587500 https_client.c:593 Released used io event: 0x7fc3d15f20
[D] 1709005661.587513 https_client.c:346 6C7E: curl request succeeded
[D] 1709005661.587521 https_client.c:439 6C7E: CURLINFO_NUM_CONNECTS: 0
[D] 1709005661.587524 https_client.c:451 6C7E: CURLINFO_EFFECTIVE_URL: https://dns.google/dns-query
[D] 1709005661.587527 https_client.c:458 6C7E: CURLINFO_HTTP_VERSION: 1.1
[D] 1709005661.587531 https_client.c:488 6C7E: Times: 0.000108, 0.000000, 0.000000, 0.000434, 0.267092, 0.267243
[D] 1709005661.587545 main.c:83 Received response for id: 6C7E, len: 28
[D] 1709005661.594498 main.c:112 Received request for id: 3578, len: 28
[D] 1709005661.594521 https_client.c:253 3578: Requesting HTTP/1.1
[D] 1709005661.594703 https_client.c:207 3578: * RESOLVE dns.google:443 is - old addresses discarded
[D] 1709005661.594715 https_client.c:207 3578: * Added dns.google:443:8.8.8.8,8.8.4.4 to DNS cache
[D] 1709005661.594729 https_client.c:207 3578: * STATE: INIT => CONNECT handle 0x55969a6fb0; line 1909 (connection #-5000)
[D] 1709005661.594782 https_client.c:207 3578: * Found bundle for host: 0x55968c1340 [serially]
[D] 1709005661.594830 https_client.c:207 3578: * Re-using existing connection #0 with host dns.google
[D] 1709005661.594838 https_client.c:207 3578: * STATE: CONNECT => CONNECTING handle 0x55969a6fb0; line 1965 (connection #0)
[D] 1709005661.594844 https_client.c:207 3578: * [CONN-0-0] connect(block=0)-> 0, done=1
[D] 1709005661.594849 https_client.c:207 3578: * STATE: CONNECTING => PROTOCONNECT handle 0x55969a6fb0; line 2073 (connection #0)
[D] 1709005661.594898 https_client.c:207 3578: * STATE: PROTOCONNECT => DO handle 0x55969a6fb0; line 2092 (connection #0)
[D] 1709005661.595259 https_client.c:207 3578: > POST /dns-query HTTP/1.1
[D] 1709005661.595264 https_client.c:207 3578: > Host: dns.google
[D] 1709005661.595266 https_client.c:207 3578: > User-Agent: https_dns_proxy/0.3
[D] 1709005661.595268 https_client.c:207 3578: > Accept: application/dns-message
[D] 1709005661.595270 https_client.c:207 3578: > Content-Type: application/dns-message
[D] 1709005661.595272 https_client.c:207 3578: > Content-Length: 28
[D] 1709005661.595282 https_client.c:207 3578: * STATE: DO => DID handle 0x55969a6fb0; line 2199 (connection #0)
[D] 1709005661.595289 https_client.c:207 3578: * STATE: DID => PERFORMING handle 0x55969a6fb0; line 2318 (connection #0)
[D] 1709005661.595306 https_client.c:207 3578: * Curl_readwrite(handle=0x55969a6fb0) -> 0
[D] 1709005661.595322 https_client.c:603 Reserved new io event: 0x7fc3d15f20
[D] 1709005661.867007 https_client.c:207 3578: * Mark bundle as not supporting multiuse
[D] 1709005661.867022 https_client.c:207 3578: * HTTP 1.1 or later with persistent connection
[D] 1709005661.867027 https_client.c:207 3578: < HTTP/1.1 200 OK
[D] 1709005661.867033 https_client.c:207 3578: < X-Content-Type-Options: nosniff
[D] 1709005661.867041 https_client.c:207 3578: < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[D] 1709005661.867045 https_client.c:207 3578: < Date: Tue, 27 Feb 2024 03:47:45 GMT
[D] 1709005661.867049 https_client.c:207 3578: < Cache-Control: private, max-age=0
[D] 1709005661.867054 https_client.c:207 3578: < Content-Type: application/dns-message
[D] 1709005661.867057 https_client.c:207 3578: < Server: HTTP server (unknown)
[D] 1709005661.867062 https_client.c:207 3578: < Content-Length: 28
[D] 1709005661.867065 https_client.c:207 3578: < X-XSS-Protection: 0
[D] 1709005661.867067 https_client.c:207 3578: < X-Frame-Options: SAMEORIGIN
[D] 1709005661.867070 https_client.c:207 3578: < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
[D] 1709005661.867098 https_client.c:207 3578: * readwrite_data(handle=0x55969a6fb0) -> 0
[D] 1709005661.867104 https_client.c:207 3578: * Curl_readwrite(handle=0x55969a6fb0) -> 0
[D] 1709005661.867111 https_client.c:207 3578: * STATE: PERFORMING => DONE handle 0x55969a6fb0; line 2517 (connection #0)
[D] 1709005661.867116 https_client.c:207 3578: * multi_done: status: 0 prem: 0 done: 0
[D] 1709005661.867134 https_client.c:207 3578: * Connection #0 to host dns.google left intact
[D] 1709005661.867151 https_client.c:593 Released used io event: 0x7fc3d15f20
[D] 1709005661.867164 https_client.c:346 3578: curl request succeeded
[D] 1709005661.867172 https_client.c:439 3578: CURLINFO_NUM_CONNECTS: 0
[D] 1709005661.867174 https_client.c:451 3578: CURLINFO_EFFECTIVE_URL: https://dns.google/dns-query
[D] 1709005661.867177 https_client.c:458 3578: CURLINFO_HTTP_VERSION: 1.1
[D] 1709005661.867181 https_client.c:488 3578: Times: 0.000100, 0.000000, 0.000000, 0.000550, 0.272248, 0.272403
[D] 1709005661.867196 main.c:83 Received response for id: 3578, len: 28
[D] 1709005661.869917 main.c:112 Received request for id: 15F8, len: 28

**Comment by baranyaib90** [comment]
According to the logs, I do not see any issues at all. Https querry to Google seems to be just fine. 
I recommend to check packet capture of the DNS traffic on 127.0.0.1:2023.

**Comment by aarond10** [comment]
Please reopen if still an issue.
