### ISSUE TITLE
Bootstrap trust

### ISSUE THREAD

**Issue by orent** [aarond10/https_dns_proxy#17]
This is an example or how to embed a trusted certificate to be used by curl:
https://github.com/curl/curl/blob/master/docs/examples/cacertinmem.c

This can help if the certificate pack in the OS is outdated, misconfigured or has extra certificates injected into it for a MITM attack. 

The certificate to be embedded should the GeoTrust CA signing Google certs:

https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem

**Comment by daztucker** [comment]
The down side of that approach is that it will add a dependency on OpenSSL that it does not currently have (OpenWRT, for example, builds libcurl with mbedtls instead).

**Comment by aarond10** [comment]
Yeah, I tend to think this is overkill. It's possible that someone might mitm 8.8.8.8 AND have a rouge google.com cert AND mitm dns.google.com, but if that's the situation you might look at pinning a cert yourself via a patch to the code (https://curl.haxx.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html). I've avoided this as it felt paranoid and maintaining it independent of the cert owners sounds cumbersome and prone to occasional breakage.
