### ISSUE TITLE
Firewall rules not removed when disabling Force Router DNS

### ISSUE THREAD

**Issue by mdsharpe** [aarond10/https_dns_proxy#170]
The setting `Force Router DNS` is enabled by default when installing `luci-app-https-dns-proxy`.

It appears that this setting adds four firewall rules, that are not visible in the OpenWRT UI (Network > Firewall).

The rules are not removed when turning off `Force Router DNS`. The only way to remove them is by command line.

**Comment by stangri** [comment]
@mdsharpe this issue should be create in openwrt/luci repository and you may want to tag/assign me to it. But you'll need to provide more information, including the output of `ubus call system board`, versions of both the principal package and the luci app, as well as step-by-step of what are you doing/testing.
