### ISSUE TITLE
Adguard (Standart) proxy instance on openwrt doesn't work

### ISSUE THREAD

**Issue by navhawk80** [aarond10/https_dns_proxy#171]
Hello,
If I add Adguard (Standart) proxy instance on openwrt it doesn't work yet.
I think the reason is that in config the option resolver_url is 'https://dns.adguard.com/dns-query' but it should be 'https://dns.adguard-dns.com/dns-query'. It I manually add correct value all works as expected.
May you look at the issue and correct it?
Thank you.
PS For Adguard family the same issue. In config option resolver_url is 'https://dns-family.adguard.com/dns-query' but it should be https://family.adguard-dns.com/dns-query

**Comment by aarond10** [comment]
This is the repository for the binary, not the openwrt integration. @stangri  Is this something in the presets for OpenWRT?

**Comment by stangri** [comment]
@aarond10 yes, the luci (WebUI) app for OpenWrt has some preset providers. 

@navhawk80 this is a very wrong place to create an issue for your problem. The proper place would be openwrt/luci repo. 

Create an issue there, indicating your versions of:
* OpenWrt
* https-dns-proxy
* luci-app-https-dns-proxy

**Comment by navhawk80** [comment]
Thanks for your time. Than I close it here and will reopen it in openwrt/luci repo.
