### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by cortadocodes** [aarond10/https_dns_proxy#172]
Is there a changelog, list of tags, or list of artifacts/binaries with version numbers somewhere? I can't work out what the latest version is

**Comment by baranyaib90** [comment]
There is no changelog, only the git commit messages.
At the moment, there are no tags, releases (artifacts/binaries).
Version is generated from the used commit date and hash at compilation. Example:
```
$ ./https_dns_proxy -V
2024.10.19-ae93cd1
```

**Comment by aarond10** [comment]
There hasn't really been enough churn to do changelogs. Changes aren't that
frequent.

**Comment by cortadocodes** [comment]
I think it would be useful to at least tag releases even if they're only yearly

**Comment by aarond10** [comment]
There aren't yearly release. Releases happen when they happen and always follow tip of tree.  Openwrt cuts it's own binaries. You can use the `-V` option as stated above to get a useful indicator (usually) of how old it is.
