### ISSUE TITLE
issues with curl 8.9.0

### ISSUE THREAD

**Issue by stangri** [aarond10/https_dns_proxy#174]
@aarond10 @baranyaib90 I've already tagged you gentlemen in the downstream issue: https://github.com/openwrt/packages/issues/24693 but I wonder if the https_dns_proxy has been successfully tested on generic Linux distributions with curl/libcurl 8.9.0?

**Comment by aarond10** [comment]
Hi! I'm running with 8.8.0 ATM. I'll give it a go with 8.9.0 this afternoon.

**Comment by stangri** [comment]
Sorry @aarond10 did you reopen this because you did experience issues with 8.9.0 or was it an accidental closure?

**Comment by aarond10** [comment]
> Sorry @aarond10 did you reopen this because you did experience issues with 8.9.0 or was it an accidental closure?
Accidental closure. Sorry. I still haven't tried. Will try a bit later today.

**Comment by Matthaiks** [comment]
Yes, 8.9.0 was the culprit.

**Comment by AcidSlide** [comment]
confirming `curl 8.9.1` fixed the issue on OpenWRT
