### ISSUE TITLE
Not getting log output until I Ctrl-c

### ISSUE THREAD

**Issue by wheelerlaw** [aarond10/https_dns_proxy#19]
If I run `https_dns_proxy` and don't provide the `-l` argument, the output that I would expect to appear in stdout doesn't appear until I kill the program with `ctrl` + `c`. 

For example:
```
wlaw@DEV-M-234SW:~/https_dns_proxy$ ./https_dns_proxy -t http://localhost:3128 -v
^C[W] 1511909566.963236 dns_poller.c:43 DNS lookup failed: 16
[W] 1511909566.963253 dns_poller.c:43 DNS lookup failed: 16
[W] 1511909566.963266 dns_poller.c:43 DNS lookup failed: 16
[W] 1511909566.963268 dns_poller.c:43 DNS lookup failed: 16
[W] 1511909566.963270 dns_poller.c:43 DNS lookup failed: 16
wlaw@DEV-M-234SW:~/https_dns_proxy$ 
```

I would expect that output to be printed to stdout _before_ I hit `ctrl` + `c`, but instead it all gets written upon program close.

**Comment by aarond10** [comment]
Can you try using 127.0.0.1 instead of localhost? I'm wondering if localhost resolution is failing due to dependence on DNS. 😄
