### ISSUE TITLE
Default to (1.1.1.1 / 1.0.0.1) Cloudflare's DNS-over-HTTPS service

### ISSUE THREAD

**Issue by opav** [aarond10/https_dns_proxy#32]
https://blog.cloudflare.com/announcing-1111/

Please default to the new Cloudflare 1.1.1.1/1.0.0.1 doh service.  

Since users are seeking privacy by using this proxy app, it doesn't make sense to continue with Google's service since they likely are already logging, processing and monetizing our DNS queries.

**Comment by aarond10** [comment]
Cloudflare support added. Closing.
