### ISSUE TITLE
any mt7620a release for openwrt 15.05.1?

### ISSUE THREAD

**Issue by qokelate** [aarond10/https_dns_proxy#35]
Any mt7620a released ipk for openwrt 15.05.1?  Install failed.
```
Unknown package 'https_dns_proxy'.
Collected errors:
 * opkg_install_cmd: Cannot install package https_dns_proxy.
```

**Comment by aarond10** [comment]
I can't check ATM but I think I might have screwed up the docs here. Can you try https-dns-proxy (dashes, not underscores) and let me know how you go?

**Comment by daztucker** [comment]
The package name is https_dns_proxy: https://openwrt.org/packages/pkgdata/https_dns_proxy.

It exists in lede-17.01 and newer (https://github.com/openwrt/packages/tree/lede-17.01/net/https-dns-proxy) but does not exist in openwrt 15.01 and older (https://github.com/openwrt/packages/tree/for-15.05/net/https-dns-proxy).

**Comment by tapper82** [comment]
15.1 is old update to lede 17.1.4 or the new openwrt 18.6

**Comment by qokelate** [comment]
OK, thanks!
