### ISSUE TITLE
compile bug

### ISSUE THREAD

**Issue by wang20150419** [aarond10/https_dns_proxy#4]
options.c:36:26: error: 'optarg' undeclared (first use in this function)
       opt->listen_addr = optarg;

**Comment by aarond10** [comment]
What platform are you building on? On linux, getopt/optarg are defined in unistd.h. I haven't tried compilation on any other OS so far.

**Comment by wang20150419** [comment]
my compile platform: OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.

**Comment by aarond10** [comment]
That's really odd.. Are you changing any build flags? Something like this?

http://stackoverflow.com/questions/22575940/getopt-not-included-implicit-declaration-of-function-getopt

I'll look at importing the getopt header directly where possible.

**Comment by wang20150419** [comment]
yes, I add compile parameter: -std=c99, for fixing for( int i = 0; i < ... )

**Comment by aarond10** [comment]
Ah, that explains it. Are you adding functionality? Anything that would be handy to roll back into this repository? 

I have intentionally avoided C++ to avoid having to link against libstdc++ (or statically link). I wanted the executable to be as small as possible to run on embedded devices.

**Comment by ivyswen** [comment]
`Scanning dependencies of target https_dns_proxy
[ 11%] Building C object CMakeFiles/https_dns_proxy.dir/src/https_client.c.o
/home/ivys/ssr/https_dns_proxy/src/https_client.c: In function ‘https_client_init’:
/home/ivys/ssr/https_dns_proxy/src/https_client.c:172:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < FD_SETSIZE; i++)
   ^
/home/ivys/ssr/https_dns_proxy/src/https_client.c:172:3: note: use option -std=c99 or -std=gnu99 to compile your code
In file included from /usr/include/curl/curl.h:2283:0,
                 from /home/ivys/ssr/https_dns_proxy/src/https_client.c:5:
/home/ivys/ssr/https_dns_proxy/src/https_client.c:177:52: error: ‘CURLPIPE_MULTIPLEX’ undeclared (first use in this function)
   curl_multi_setopt(c->curlm, CURLMOPT_PIPELINING, CURLPIPE_MULTIPLEX);
                                                    ^
/home/ivys/ssr/https_dns_proxy/src/https_client.c:177:52: note: each undeclared identifier is reported only once for each function it appears in
/home/ivys/ssr/https_dns_proxy/src/https_client.c: In function ‘https_client_cleanup’:
/home/ivys/ssr/https_dns_proxy/src/https_client.c:199:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < FD_SETSIZE; i++) {
   ^
make[2]: *** [CMakeFiles/https_dns_proxy.dir/src/https_client.c.o] Error 1
make[1]: *** [CMakeFiles/https_dns_proxy.dir/all] Error 2
make: *** [all] Error 2`

**Comment by aarond10** [comment]
Ah, sorry. I hadn't properly checked this.
Should be fixed now in commit 9104247. 
Please let me know if you still have issues.
