### ISSUE TITLE
Not binding to port when run from Systemd

### ISSUE THREAD

**Issue by wheelerlaw** [aarond10/https_dns_proxy#41]
I am trying to write a systemd unit file to handle running https_dns_proxy as a system service. However, for some reason https_dns_proxy doesn't want to listen for connections when its run by systemd. When I take the command that systemd executes to run https_dns_proxy and run it manually through the command line, it works fine however. 

More details at this [StackOverflow question](https://stackoverflow.com/questions/50803735/program-not-listening-when-started-with-systemd):

When I run a program the command line that listens on a specified address and port, it works perfectly fine:

    /usr/bin/https_dns_proxy -t http://localhost:3128 -a 127.0.0.1 -p 5054

Give me:

    dig @127.0.0.1 -p 5054 www.amazon.com
    
    ; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> @127.0.0.1 -p 5054 www.amazon.com
    ; (1 server found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5356
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
    
    ;; QUESTION SECTION:
    ;www.amazon.com.			IN	A
    
    ;; ANSWER SECTION:
    www.amazon.com.		162	IN	CNAME	www.cdn.amazon.com.
    www.cdn.amazon.com.	46	IN	CNAME	www.amazon.com.edgekey.net.
    www.amazon.com.edgekey.net. 105	IN	CNAME	e15316.ci.akamaiedge.net.
    e15316.ci.akamaiedge.net. 6	IN	A	104.117.47.132
    
    ;; Query time: 29 msec
    ;; SERVER: 127.0.0.1#5054(127.0.0.1)
    ;; WHEN: Mon Jun 11 13:52:15 EDT 2018
    ;; MSG SIZE  rcvd: 158

However, when I run the program through systemd, it does not work:

    $ sudo systemctl status https-dns-proxy.service 
    ● https-dns-proxy.service - Resolve DNS queries over HTTPS.
       Loaded: loaded (/lib/systemd/system/https-dns-proxy.service; enabled; vendor preset: enabled)
       Active: inactive (dead) since Mon 2018-06-11 13:52:09 EDT; 1min 20s ago
      Process: 8338 ExecStart=/usr/bin/https_dns_proxy ${DAEMON_ARGS} (code=killed, signal=TERM)
     Main PID: 8338 (code=killed, signal=TERM)
    $ sudo systemctl start https-dns-proxy.service 
    $ sudo systemctl status https-dns-proxy.service 
    ● https-dns-proxy.service - Resolve DNS queries over HTTPS.
       Loaded: loaded (/lib/systemd/system/https-dns-proxy.service; enabled; vendor preset: enabled)
       Active: active (running) since Mon 2018-06-11 13:54:31 EDT; 2s ago
     Main PID: 12635 (https_dns_proxy)
        Tasks: 1 (limit: 4915)
       CGroup: /system.slice/https-dns-proxy.service
               └─12635 /usr/bin/https_dns_proxy -t http://localhost:3128 -a 127.0.0.1 -p 5054
    
    Jun 11 13:54:31 DEV-M-20T3W systemd[1]: Started Resolve DNS queries over HTTPS..

    $ dig @127.0.0.1 -p 5054 www.amazon.com
    
    ; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> @127.0.0.1 -p 5054 www.amazon.com
    ; (1 server found)
    ;; global options: +cmd
    ;; connection timed out; no servers could be reached

Why when running the program with systemd does the app no listen on the specified port?

The unit file:

    [Unit]
    Description=Resolve DNS queries over HTTPS. 
    After=network.target
    
    [Service]
    User=nobody
    Group=nogroup
    EnvironmentFile=-/etc/default/https-dns-proxy
    CapabilityBoundingSet=CAP_NET_BIND_SERVICE
    ExecStart=/usr/bin/https_dns_proxy ${DAEMON_ARGS}
    
    [Install]
    WantedBy=multi-user.target

**Comment by aarond10** [comment]
I'm not very familiar with systemd configs but a few things that stand out are:

1. CAP_NET_BIND_SERVICE is for [privileged](https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html) ports. 5054 isn't priviledged so I assume it shouldn't be needed.
2. The log you post says the task was started 2 seconds ago which makes me think it might be crash-looping. Can you add -vvvv to the args and then look at the systemd journal to see if it's failing somewhere unexpected?

Note also you're launching this as nobody/nogroup (rather than as, say, root and dropping permissions). This shouldn't be an issue, but may be worth seeing if that fixes it to rule out nobody being restricted from opening listening sockets or something.

**Comment by aarond10** [comment]
This is super stale. Closing for now. I'm not convinced it's a problem with the binary itself. Please let me know if you disagree.
