### ISSUE TITLE
openwrt package: start second instance by default

### ISSUE THREAD

**Issue by apeganz** [aarond10/https_dns_proxy#43]
Hi!

I just discovered this project and think it's awesome! Especially that you also provide an openwrt package so it is easy to use.

Related to #29 and #32:
Something that would be icing on the cake would be support for multiple DNS providers in an easy to use way too. The quickest way to achieve this probably is to start multiple instances listening at different ports and let the users configure dnsmasq (or whatever) to use all of them as DNS servers.
In the case of openwrt this way the desired service(s) can be selected even using luci via the "DHCP and DNS/DNS forwardings" setting. And it's a change that should be easy to transplant to a DoT proxy as well.

Maybe you could change the startup script so it launched a second process listening at e.g. 5153 that used the cloudflare DNS? Users could then very easily point dnsmasq to their preferred service, or use both.

In the long run maybe a (luci-editable?) config file where users can specify any number of DoH providers, query URLs, and ports could be in the cards.

Brgds!

**Comment by aarond10** [comment]
Glad you find this useful!

By chance(?) there is also someone else looking to write some new [OpenWRT config scripts](https://github.com/openwrt/packages/pull/6853). They're looking to run both Google and Cloudflare in parallel on different ports like this to allow DNS fallback across providers. 

Your long term vision also sounds like a nice place to target but I haven't looked at luci scripts at all yet and am unlikely to until I finish adding all the DNS types I'm still lacking (RRSIG, etc).

I'll close this out for now. Always happy for good quality pull requests if you have the coding knowledge!

**Comment by aarond10** [comment]
FYI: New package scripts landed a few days ago. You'll need trunk to get them for now. Runs both providers on two ports.
