### ISSUE TITLE
openwrt package: daemon does not drop privileges under procd

### ISSUE THREAD

**Issue by tofurky** [aarond10/https_dns_proxy#44]
currently, main.c only drops privileges if daemonizing:

https://github.com/aarond10/https_dns_proxy/blob/79780523faf5ba1f3314596bd57170d4435f84cb/src/main.c#L212-L221

under procd (i.e. when not daemonized) this code path isn't reached and therefore https_dns_proxy doesn't drop privileges as directed via the user and group options in /etc/config/https_dns_proxy.

i was using my own package up until now and worked around this by using an init script without `USE_PROCD=1` and instead starting with `-d`.

maybe main.c should drop privileges if the daemon is started with `-u` / `-g` unconditionally, instead of just when the `-d` switch is used? or perhaps `USE_PROCD` should be dropped from the init script?

this mentions procd, but i'd imagine the same would happen with e.g. systemd.

if you'd like i can submit a PR which drops privileges unconditionally if `-u` / `-g` are provided. thanks!

**Comment by aarond10** [comment]
Excellent idea. Would love a pull request for this!

**Comment by tofurky** [comment]
i was thinking about doing something like this.

it kind of takes a step backwards in that it doesn't drop privileges by default anymore, though at least debian and openwrt use "nogroup" instead of the previously hard-coded "nobody" group, so it wasn't dropping gid in many cases anyways.

this is so i could use strlen() to see if they were provided instead of adding in bool or similar into the otherwise pristine getopt() switch statement. executing with e.g. -u someuser -g "" falls through the logic however - it doesn't cause an error nor does it trigger a setgid().

that said, if it looks OK i will open a PR - otherwise i'm open to feedback/suggestions.

```

diff --git a/src/main.c b/src/main.c
index f92afb5..dc5acf8 100644
--- a/src/main.c
+++ b/src/main.c
@@ -209,13 +209,17 @@ int main(int argc, char *argv[]) {
   dns_server_init(&dns_server, loop, opt.listen_addr, opt.listen_port,
                   dns_server_cb, &app);
 
+  // opt.group / opt.user being non-zero length means that they've been
+  // explicitly provided via cmdline and have been successfully mapped to
+  // their corresponding gid / uid.
+  if (strlen(opt.group) && setgid(opt.gid)) {
+    FLOG("Failed to set gid.");
+  }
+  if (strlen(opt.user) && setuid(opt.uid)) {
+    FLOG("Failed to set uid.");
+  }
+
   if (opt.daemonize) {
-    if (setgid(opt.gid)) {
-      FLOG("Failed to set gid.");
-    }
-    if (setuid(opt.uid)) {
-      FLOG("Failed to set uid.");
-    }
     // daemon() is non-standard. If needed, see OpenSSH openbsd-compat/daemon.c
     daemon(0, 0);
   }
diff --git a/src/options.c b/src/options.c
index f5a7683..d4455eb 100644
--- a/src/options.c
+++ b/src/options.c
@@ -20,8 +20,8 @@ void options_init(struct Options *opt) {
   opt->logfd = -1;
   opt->loglevel = LOG_ERROR;
   opt->daemonize = 0;
-  opt->user = "nobody";
-  opt->group = "nobody";
+  opt->user = "";
+  opt->group = "";
   opt->uid = -1;
   opt->gid = -1;
   //new as from https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers
@@ -80,13 +80,15 @@ int options_parse_args(struct Options *opt, int argc, char **argv) {
       exit(EXIT_FAILURE);
     }
   }
-  if (opt->daemonize) {
+  if (strlen(opt->user)) {
     struct passwd *p;
     if (!(p = getpwnam(opt->user)) || !p->pw_uid) {
       printf("Username (%s) invalid.\n", opt->user);
       return -1;
     }
     opt->uid = p->pw_uid;
+  }
+  if (strlen(opt->group)) {
     struct group *g;
     if (!(g = getgrnam(opt->group)) || !g->gr_gid) {
       printf("Group (%s) invalid.\n", opt->group);
```

**Comment by aarond10** [comment]
Is there something that stops "NULL" being used?

**Comment by tofurky** [comment]
i tried to avoid adding additional variables e.g. bool user_isset / bool group_isset to keep track of if -g and -u are actually provided via argv, even if they're provided as empty strings. but that'd be the way to tell the difference, and then the "drop permissions by default if daemonized" behavior could be retained.

maybe it could be added to the opt struct too. if those variables were introduced then it wouldn't be necessary to reuse strlen(opt.user)/strlen(opt.group) as an indicator if -g/-u were provided in main.c.

i think uid/gid could be also utilized for this purpose (e.g. initialized as -2, set to -1 if -u/-g are provided in the gettopt case statement, and then >= 0 means to change uid to that). kinda hacky though.

**Comment by aarond10** [comment]
I think it can be done without strlen() or extra vars but it was a bit long-winded to explain so I've just done two commits myself. (See 915211bdc1) Is this the functionality you were after?

**Comment by tofurky** [comment]
yep, thanks for makign those changes!

**Comment by tofurky** [comment]
btw 915211bdc1f697cae80cb8e49ca23cd88973b920 should be "privileges". quick, you might be able to get a push --force in before anyone clones the repo ;)

**Comment by aarond10** [comment]
Ah, whoops. Fixed now! I'll close this issue.
