### ISSUE TITLE
Secure HTTPS

### ISSUE THREAD

**Issue by geekdrive** [aarond10/https_dns_proxy#46]
No attempt is made by https-dns-proxy to secure the TLS in HTTPS, such as

curl_easy_setopt(ctx->curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
curl_easy_setopt(curl, CURLOPT_SSL_CIPHER_LIST, "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH");

which means that the strength of encryption is left to the OS (or the packager of openssl for that distro). Not saying these good settings and I am no expert in crypto, and these will break older distros but I prefer security by default and hate applications that ship with known insecure defaults.

**Comment by aarond10** [comment]
TLS 1.2 is forced and has been as of 694bf6d82c237f7a746979039fbf9274a0f0d1e0.
I've avoided maintaining a cipher list myself as this is not something I'm likely to stay on top of. Hope that helps.
