### ISSUE TITLE
Can you make an option for the user to decide whether to get the A result or the AAAA result or the result of ANY?

### ISSUE THREAD

**Issue by PussAzuki** [aarond10/https_dns_proxy#49]
Could you make an option for the user to decide whether to get the A result or the AAAA result or the result of ANY?
Not everyone has an ipv6 address. Those who don't have a native ipv6 address have to use a tunnel. And your software is very good.However, your software has only a backup mechanism and no complementary mechanism.which makes the software somewhat inadequate.
If you can do it ,I would be appreciate

Translated by Google Translate

**Comment by aarond10** [comment]
That would be breaking standards IIUC. It sounds like you are using some non-standard environment. If you only have IPv4, your host shouldn't be trying to use AAAA records.  ANY queries return both A (type 1) and AAAA (type 28) records. Your host should choose the most appropriate.

**Comment by PussAzuki** [comment]
Yes, I am using a 6in4 tunnel, which is why I need to use a DoH service with different EDNS client subnets.
