### ISSUE TITLE
Could you add proxy support?

### ISSUE THREAD

**Issue by rampageX** [aarond10/https_dns_proxy#5]
Some country like China blocked the IP of dns.google.com, so we need proxy to work. I can hardcode add:

```
curl_easy_setopt(ctx->curl, CURLOPT_PROXY, "socks5://127.0.0.1:9050");
```

to `https_client.c` to use proxy, it's work, but this is bad way i know. It is shame i know nothing about C++ language...

So, could you add native proxy support? may be `-t http://127.0.0.1:8080` or `-t socks5://127.0.0.1:9050` etc...

Thanks!

**Comment by aarond10** [comment]
Sounds like a pretty easy and pretty useful feature request. I'm a bit busy this week but will try to find time to do this next week.

**Comment by aarond10** [comment]
Done. Please let me know if you have any issues.

**Comment by rampageX** [comment]
Work like a charm, Thanks @aarond10 !
