### ISSUE TITLE
parse_time timezone offset TODO isn't accurate

### ISSUE THREAD

**Issue by bmrzycki** [aarond10/https_dns_proxy#51]
@aarond10 , I noticed the following `TODO` while browsing your commit for #50 . 
https://github.com/aarond10/https_dns_proxy/blob/master/src/json_to_dns.c#L304

I went and looked at glibc in `time/mktime.c`, function `ranged_convert()` they treat a negative `tm_sec` as an error, which is called by `__mktime_internal()`.  I suspect the negative `tm_sec` value is being ignored and converted to 0 which probably isn't what you want.

I have an alternate `parse_timezone` routine available, should you find it useful:

```
uint32_t parse_time(const char *timestr) {
    struct tm tm;
    memset(&tm, 0, sizeof(tm));
    if (sscanf(timestr, "%04d%02d%02d%02d%02d%02d",
	       &tm.tm_year, &tm.tm_mon, &tm.tm_mday,
	       &tm.tm_hour, &tm.tm_min, &tm.tm_sec) != 6) {
	return 0;
    }

    tzset();
    tm.tm_year -= 1900;
    tm.tm_mon -= 1;

    if (tm.tm_year < 0)
	return 0; /* Treat years before 1900 as invalid. */
    if (tm.tm_mon < 0 || tm.tm_mon > 11)
	return 0;
    if (tm.tm_mday < 1 || tm.tm_mday > 31)
	return 0; /* Note zero is an invalid mday */
    if (tm.tm_hour < 0 || tm.tm_hour > 23)
	return 0;
    if (tm.tm_min < 0 || tm.tm_min > 59)
	return 0;
    if (tm.tm_sec < 0 || tm.tm_sec > 60)
	return 0; /* may contain a leap second */

    time_t t = mktime(&tm);
    if (t == -1)
	return 0;
    /* According to tzset(3) the global variable timezone is set to the
     * number of seconds needed to alter a GMT/UTC time into a local
     * time. Values west of GMT are positive, east of GMT are negative.
     * Because times west of GMT are earlier, we must subtract timezone.
     * In the case of timezones west of the GMT it will remove seconds
     * and in the case of timezones east of GMT it will add seconds
     * by subtracting a negative value.
     */
    t -= timezone;

    /* The contents of timezone is *not* adjusted for daylight savings.
     * We must manually adjust an hour if it is in effect.
     */
    t += tm.tm_isdst * 3600;
    return (uint32_t)t;
}
```

**Comment by bmrzycki** [comment]
The daylight savings time adjustment is particularly troublesome. Because `mktime()` takes a `struct tm` in local time format, and the string we're parsing is in GMT there is an error adjusting for daylight savings time for times that fall right in the daylight window.

For example, let's use March 10, 2019 at 1:59AM GMT and the local timezone is USA Central (-6 normal, -5 daylight). When `mktime()` is called it treats that as a local time and `tm_isdst` is set to 0. However, that time is GMT and is actually 5 hours ahead and should be converted to March 10, 2019 6:59AM CDT. If this date was passed in `tm_isdst` would be correctly set to 1 on return.

This hurts my head. :)

I don't know how important `parse_time()` is to the overall functioning of the proxy tool and maybe we don't care that dates in a 6 hour window are off by 1 hour. But if we do then the adjustment has to be done *before* calling `mktime()` and is very tricky to subtract from all the fields without going above or below their value ranges.

I've done a bunch of searching on the issue and found very little to help solve this.

**Comment by bmrzycki** [comment]
I found a [stack-exchange equation](https://stackoverflow.com/questions/9076494/how-to-convert-from-utc-to-local-time-in-c) that might prove interesting:
```
tm_sec + tm_min*60 + tm_hour*3600 + tm_yday*86400 +
    (tm_year-70)*31536000 + ((tm_year-69)/4)*86400 -
    ((tm_year-1)/100)*86400 + ((tm_year+299)/400)*86400
```

I have not worked through all of it to verify its correctness, and we have to calculate `tm_yday` from the inputted month and day. Here's some scratch C code that may just do what we need without any library calls for time **ASSUMING THE EQUATION IS CORRECT**:

```
int yday(int year, int month, int day) {

    int sum = day;

    if (year < 1 || month < 1 || day < 1)
	return -1;

    if (month == 1)
	return sum;
    sum += 31; /* Jan */
    if (month == 2)
	return sum;
    sum += 28; /* Feb */

    if ((year % 400 == 0) || ((year % 100 != 0) && (year % 4 == 0)))
	sum++; /* Leap year, add one day in Feb */

    if (month == 3)
	return sum;
    sum += 31; /* Mar */
    if (month == 4)
	return sum;
    sum += 30; /* Apr */
    if (month == 5)
	return sum;
    sum += 31; /* May */
    if (month == 6)
	return sum;
    sum += 30; /* Jun */
    if (month == 7)
	return sum;
    sum += 31; /* Jul */
    if (month == 8)
	return sum;
    sum += 31; /* Aug */
    if (month == 9)
	return sum;
    sum += 30; /* Sep */
    if (month == 10)
	return sum;
    sum += 31; /* Oct */
    if (month == 11)
	return sum;
    sum += 30; /* Nov */
    if (month == 12)
	return sum;

    return -1;
}

uint32_t parse_time(const char *timestr) {
    int y = 0, m = 0, d = 0;
    int H = 0, M = 0, S = 0;
    if (sscanf(timestr, "%04d%02d%02d%02d%02d%02d",
	       &y, &m, &d, &H, &M, &S) != 6) {
	return 0;
    }

    if (y < 1970)
	return 0; /* Jan 1 1970 is the epoch. */
    if (m < 1 || m > 12)
	return 0;
    if (d < 1 || d > 31)
	return 0;
    if (H < 0 || H > 23)
	return 0;
    if (M < 0 || M > 59)
	return 0;
    if (S < 0 || S > 60)
	return 0; /* Note S may contain a leap second. */

    return S + M * 60 + H * 3600 + yday(y, m, d) * 86400 +
	(y - 70) * 31536000 + ((y - 69) / 4) * 86400 -
	((y - 1) / 100) * 86400 + ((tm_year + 299) / 400) * 86400;
}
```

**Comment by aarond10** [comment]
I've fixed the parser and added some tests, factored all these new util functions out into set of unit tests and a utils.{cc,h} file pair. Still a lot more worth doing, but it's a start. 👍

**Comment by bmrzycki** [comment]
Awesome, thank you for working on this @aarond10 !
