### ISSUE TITLE
A strange problem

### ISSUE THREAD

**Issue by Typhonling** [aarond10/https_dns_proxy#52]
openwrt 18.02+https_dns_proxy 2018-04-23-3

When use google.com + hdp, everything is fine.
When use rubyfish.cn + hdp , WIN10 LTSC can't get IP, but no problem with Android.
Check dnsmasq's log, google & rubyfish reply the same IP.
Then use WireShark to capture the DNS reply message, rubyfish's reply message has some error:
```
[Malformed Packet: DNS]
    [Expert Info (Error/Malformed): Malformed Packet (Exception occurred)]
        [Malformed Packet (Exception occurred)]
        [Severity level: Error]
        [Group: Malformed]
```
rubyfish/hdp/LTSC, I don't know which one is the culprit.

**Comment by aarond10** [comment]
I'm not sure I can help. I don't understand these other pieces of software.
