### ISSUE TITLE
can't connect to cloudflare dns if using direct ip address https://1.1.1.1/

### ISSUE THREAD

**Issue by gitgayhub** [aarond10/https_dns_proxy#53]
I tried to use 1.1.1.1 as t he name resolver, https://1.1.1.1/dns-query?ct=application/dns-json& but got a connection timeout error, I can only use the domain name https://cloudflare-dns.com/

same situation for https://9.9.9.9/

**Comment by aarond10** [comment]
Are you sure you're not conflating concepts?

1.1.1.1 and 9.9.9.9 are for regular DNS queries. These are sent
unencrypted, typically over UDP.
This program resolves a https server and converts DNS requests
sent/received as JSON to UDP for use on your local network.

**Comment by gitgayhub** [comment]
Yes I'm sure, https://1.1.1.1/ supports DoH

Try this
curl "https://1.1.1.1/dns-query?ct=application/dns-json&name=google.com&type=A"

**Comment by gitgayhub** [comment]
Also try curl "https://9.9.9.9/dns-query?ct=application/dns-json&name=google.com&type=A"

they both will return the json file

Please re-open the issue

**Comment by aarond10** [comment]
Ah, right you are! Apologies. I'll try to take a look tomorrow.

**Comment by Antares95** [comment]
what about https://one.one.one.one/ ?

**Comment by mark-sivill-splunk** [comment]
Is the concern that to initially bootstrap to the domain cloudflare-dns.com a clear text DNS query needs to have already taken place. If the bootstrap was able to do DNS over HTTPS ( so avoiding clear text DNS ) would this be better? The bootstrap could use something like https://1.1.1.1/dns-query?ct=application/dns-json& to start with so avoiding the initial DNS lookup.

**Comment by Nowaker** [comment]
This configuration works for me just fine:

```
config https-dns-proxy
        option listen_addr '127.0.0.1'
        option listen_port '5054'
        option user 'nobody'
        option group 'nogroup'
        option bootstrap_dns '1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001'
        option resolver_url 'https://1.1.1.1/dns-query'
```

Not sure if this is what this ticket is about, but if it is, it definitely works.

**Comment by aarond10** [comment]
Yeah, I'm closing this. I believe this was fixed a long while back.
