### ISSUE TITLE
How to resolve

### ISSUE THREAD

**Issue by mazige1997** [aarond10/https_dns_proxy#64]
https_dns_proxy/src/options.c: In function 'options_parse_args':
https_dns_proxy/src/options.c:100: error: 'O_CLOEXEC' undeclared (first use in this function)
https_dns_proxy/src/options.c:100: error: (Each undeclared identifier is reported only once
https_dns_proxy/src/options.c:100: error: for each function it appears in.)
https_dns_proxy.dir/build.make:206: recipe for target 'CMakeFiles/https_dns_proxy.dir/src/options.c.o' failed
make[5]: *** [CMakeFiles/https_dns_proxy.dir/src/options.c.o] Error 1

**Comment by aarond10** [comment]
What platform are you building on?

**Comment by aarond10** [comment]
4a480a9bccb7cf604cbc8c5828bdf0d0203e0843 should fix this.
