### ISSUE TITLE
openwrt 19.07 CURLINFO_RESPONSE_CODE: 0

### ISSUE THREAD

**Issue by a7ypically** [aarond10/https_dns_proxy#66]
Hi,

Looks like this is a curl issue but I'm putting it here so others who may look for this issue can find it.

I'm running a pre released openwrt 19.07 on x86 and I've been constantly getting periods of time where https-dns-proxy did not respond to dns queries. Looking at the logs I can see that the curl request immediately returned with a response code of zero. The proxy would recover in about a couple of minutes until the next period of curl errors.

openwrt 19.07 has curl 7.65.3 and I found an open issue with curl not detecting dead connections: https://github.com/curl/curl/issues/4246
It seems that curl 7.65.1 did not exhibit this issue and sure enough after I downgraded my curl to 7.65.1 https-dns-proxy works fine with no issue.

Also, I have two https-dns-proxy instances, one uses a socks proxy and the other do not. The one with the socks proxy did not have any issue, regardless of the curl version.

```
[D] 1569266163.986096 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.goog
le/resolve?name=google.com&type=1
[D] 1569266163.986103 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1569266163.986110 https_client.c:173 Times: 0.000062, 0.000065, 0.000065, 0.
000109, 0.000000, 0.000134
[D] 1569266163.986138 main.c:81 buflen 0
```

**Comment by aarond10** [comment]
This seems to have abated since reported. Please let me know if this is still an issue with recent versions. I cannot reproduce.
