### ISSUE TITLE
support SRV and RRSIG

### ISSUE THREAD

**Issue by moparisthebest** [aarond10/https_dns_proxy#7]
Currently getting errors like this when trying to query for certain record types:
[W] 1479503994.574179 json_to_dns.c:333 Failed to encode Answer ix 0.

You can use these examples:
dig @127.0.0.1 -p5053 srv _xmpp-client._tcp.debian.org
dig @127.0.0.1 -p5053 rrsig _xmpp-client._tcp.debian.org

Might want to check other record types too, DNSKEY and such?

**Comment by aarond10** [comment]
I never added support for either of those. Was just sticking to the original DNS RFC. I've pieced together a SRV implementation based on rfc2782 and wireshark format data. Seems to work. PTAL.

I'll have a look at rrsig next week sometime.

**Comment by aarond10** [comment]
For some context, Google's docs on the format of the responses is a bit thin so I've just stuck to the RDATA types that I figured most people would use the most. At some stage I'd like to clean this up and add support for OpenResolv as an alternative. Also happy to accept pull requests if you have time to add rrsig yourself.

**Comment by aarond10** [comment]
This has been a long time coming and I've only thoroughly tested the NSEC3 and RRSIG cases but support should be in now after commit 85354a3f2d6a256647d75844d18f6a033eb4d24f.
