### ISSUE TITLE
new version not working

### ISSUE THREAD

**Issue by golden777** [aarond10/https_dns_proxy#72]
run 
./https_dns_proxy -a 0.0.0.0 -p 5053

dig domain.com @serverip -p 5053
nothing happend

an old version workd very well

**Comment by aarond10** [comment]
Please try again with the additional commandline option `-vvv` and let me know if you see any errors.

**Comment by golden777** [comment]
> Please try again with the additional commandline option `-vvv` and let me know if you see any errors.

WARNING: Running as root without dropping privileges is NOT recommended.
----------------------------
[I] 1576622250.127878 main.c:161 Built Dec 17 2019 22:37:17.
[I] 1576622250.127995 main.c:162 System c-ares: 1.14.0
[I] 1576622250.128168 main.c:163 System libcurl: libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
[I] 1576622250.130102 dns_server.c:59 Listening on 0.0.0.0:5321
[D] 1576622250.130134 logging.c:49 initializing periodic log flush timer
[I] 1576622250.130363 main.c:228 DNS polling initialized for 'dns.google'
[D] 1576622250.132469 main.c:130 Received new IP '2001:4860:4860::8844'
[D] 1576622250.132488 dns_poller.c:56 DNS poll interval changed from 5 -> 120
[D] 1576622306.537890 main.c:99 Received request for id: f8d9, len: 52
[D] 1576622306.538234 https_client.c:58 Requesting HTTP/1.1: 0

* Added dns.google:443:2001:4860:4860::8844 to DNS cache
* Hostname dns.google was found in DNS cache
*   Trying 2001:4860:4860::8844...
* TCP_NODELAY set
* Immediate connect fail for 2001:4860:4860::8844: Network is unreachable
* Closing connection 0
[D] 1576622306.538940 https_client.c:105 CURLINFO_EFFECTIVE_URL: https://dns.google/dns-query
[D] 1576622306.538949 https_client.c:117 CURLINFO_RESPONSE_CODE: 0
[E] 1576622306.538952 https_client.c:129 CURLINFO_OS_ERRNO: 101
[D] 1576622306.538959 https_client.c:182 Times: 0.000126, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000
[D] 1576622306.539010 main.c:81 buflen 0

[D] 1576622311.537254 main.c:99 Received request for id: f8d9, len: 52
[D] 1576622311.537320 https_client.c:58 Requesting HTTP/1.1: 0

* RESOLVE dns.google:443 is already cached, 2001:4860:4860::8844 not stored!
* Added dns.google:443:2001:4860:4860::8844 to DNS cache
* Hostname dns.google was found in DNS cache
*   Trying 2001:4860:4860::8844...
* TCP_NODELAY set
* Immediate connect fail for 2001:4860:4860::8844: Network is unreachable
* Closing connection 1
[D] 1576622311.537676 https_client.c:105 CURLINFO_EFFECTIVE_URL: https://dns.google/dns-query
[D] 1576622311.537686 https_client.c:117 CURLINFO_RESPONSE_CODE: 0
[E] 1576622311.537705 https_client.c:129 CURLINFO_OS_ERRNO: 101
[D] 1576622311.537727 https_client.c:182 Times: 0.000071, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000
[D] 1576622311.537766 main.c:81 buflen 0

[D] 1576622316.537476 main.c:99 Received request for id: f8d9, len: 52
[D] 1576622316.537553 https_client.c:58 Requesting HTTP/1.1: 0

* RESOLVE dns.google:443 is already cached, 2001:4860:4860::8844 not stored!
* Added dns.google:443:2001:4860:4860::8844 to DNS cache
* Hostname dns.google was found in DNS cache
*   Trying 2001:4860:4860::8844...
* TCP_NODELAY set
* Immediate connect fail for 2001:4860:4860::8844: Network is unreachable
* Closing connection 2
[D] 1576622316.537912 https_client.c:105 CURLINFO_EFFECTIVE_URL: https://dns.google/dns-query
[D] 1576622316.537926 https_client.c:117 CURLINFO_RESPONSE_CODE: 0
[E] 1576622316.537932 https_client.c:129 CURLINFO_OS_ERRNO: 101
[D] 1576622316.537951 https_client.c:182 Times: 0.000067, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000
[D] 1576622316.537983 main.c:81 buflen 0

-----------------
thanks
i know what wrong, it's requese throw ipv6,but i don't have ipv6 address

another thing
 the  -e subnet_addr         An edns-client-subnet to use such as "203.31.0.0/16".

may be  add a feture let the client's ip address for the default -e subnet_addr not the server's ip instead, cause the clients dont't come the same aera,the CDN resolve did't same ,if works like this,then one server could serve many users.

thanks

**Comment by golden777** [comment]
just tryed -e subnet_addr ,not working

**Comment by aarond10** [comment]
Can you try with the argument -4?

**Comment by golden777** [comment]
> Can you try with the argument -4?
yes -4 works,but the -e subnet_addr not works right ,old version works right ,i'm sure 
thanks

**Comment by aarond10** [comment]
I've fixed the bad URL gen but this feature won't work with RFC8484 standard compliant resolvers.
The ECN (EDNS Client Subnet) feature is now supported as part of the DNS request itself (as with regular DNS).

e.g. 
```
# LA
$ dig www.google.com +trace +all +subnet=52.64.123.170
...
www.google.com.         300     IN      A       216.58.199.36
```
vs

```
# Sydney
$ dig www.google.com +trace +all +subnet=149.142.201.252
...
www.google.com.         300     IN      A       172.217.5.68
...
```
You'll need a DNS proxy that can add EDNS0 options to your requests if you need this going forward. I'll deprecate this feature with a warning shortly.

**Comment by aarond10** [comment]
Yes, the -e option doesn't work with the RFC-based DNS-over-HTTPS. That was
a Google-specific option that worked with the JSON API (now removed from
this binary).
