### ISSUE TITLE
Do not change user's custom config of dnsmasq

### ISSUE THREAD

**Issue by Ykidia** [aarond10/https_dns_proxy#73]
You said you maintain the package for OpenWrt as well. Then read my thoughts about your startup script /etc/init.d/https_dns_proxy.
Shortly: do not change user's custom configuration of another packages!
For example, mine configuration of dnsmasq uses ~20 dns providers: several instances for dnscrypt-proxy, several for stubby and three for https_dns_proxy (and yes, there are some others providers of DoH, not only Google and Cloudflare!). And now I suddenly discovered that startup script of your new version of https_dns_proxy crosses out all my efforts on dnsmasq config making "doh_backup_server" instead of "server". And it is not as good as it seems, because after that changes dnsmasq uses only your https_dns_proxy and none of the others specified in the config.
Are you understand? You want to help "stupid" users but if user is really stupid then nothing can help him.
Please consider to remove such "helpers" as dhcp_backup function an so on, from startup script for OpenWrt.
Thank you.

**Comment by aarond10** [comment]
I can see that you're angry but I can't quite understand what you're angry
about.
Could you explain in a bit more detail, without so much angst?

**Comment by Ykidia** [comment]
Sorry for my negative.

Explaining: I have OpenWrt with dnscrypt-proxy, stubby and https-dns-proxy installed.
I am using these configurations:

1) dnscrypt-proxy has 13 instances (including ipv6)
[code]cat /etc/config/dnscrypt-proxy
config dnscrypt-proxy 'ns1'
#       option address '127.0.0.1'
        option port '5353'
        option resolver 'securedns'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'

config dnscrypt-proxy 'ns2'
#       option address '::1'
        option port '5363'
        option resolver 'securedns-ipv6'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'


config dnscrypt-proxy 'ns3'
#       option address '127.0.0.1'
        option port '15353'
        option resolver 'd0wn-se-ns1'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'

config dnscrypt-proxy 'ns4'
#       option address '::1'
        option port '15363'
        option resolver 'd0wn-se-ns1-ipv6'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'


config dnscrypt-proxy 'ns5'
#       option address '127.0.0.1'
        option port '25353'
        option resolver 'cisco'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'

config dnscrypt-proxy 'ns6'
#       option address '::1'
        option port '25363'
        option resolver 'cisco-ipv6'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'


config dnscrypt-proxy 'ns7'
#       option address '127.0.0.1'
        option port '35353'
        option resolver 'dnscrypt.eu-dk'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'

config dnscrypt-proxy 'ns8'
#       option address '::1'
        option port '35363'
        option resolver 'dnscrypt.eu-dk-ipv6'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'


config dnscrypt-proxy 'ns9'
#       option address '127.0.0.1'
        option port '45353'
        option resolver 'dnscrypt.nl-ns0'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'

config dnscrypt-proxy 'ns10'
#       option address '::1'
        option port '45363'
        option resolver 'dnscrypt.nl-ns0-ipv6'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'


config dnscrypt-proxy 'ns11'
#       option address '127.0.0.1'
        option port '55353'
        option resolver 'dnscrypt.org-fr'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'


config dnscrypt-proxy 'ns13'
#       option address '127.0.0.1'
        option port '65353'
        option resolver 'ipredator'
        option local_cache '0'
        option block_ipv6 '0'
        option log_level '0'
[/code]
2) stubby has 16 instances (including ipv6)
[code]cat /etc/config/stubby
config stubby 'global'
       option manual '0'
       option trigger 'timed'
       option triggerdelay '10'
       list dns_transport 'GETDNS_TRANSPORT_TLS'
       option tls_authentication '1'
       option tls_query_padding_blocksize '128'
       # option tls_connection_retries '2'
       # option tls_backoff_time '3600'
       # option timeout '5000'
       # option dnssec_return_status '0'
       # option appdata_dir '/tmp/lib/stubby'
       option appdata_dir '/tmp/stubby'
       # option dnssec_trust_anchors '/var/lib/stubby/getdns-root.key'
       # option edns_client_subnet_private '1'
       option idle_timeout '10000'
       option round_robin_upstreams '1'
       list listen_address '127.0.0.1@5453'
       list listen_address '0::1@5453'
       # option log_level '7'
       # option command_line_arguments ''

# Upstream resolvers are specified using 'resolver' sections.

config resolver
       option address '1.1.1.1'
       option tls_auth_name 'cloudflare-dns.com'

config resolver
       option address '1.0.0.1'
       option tls_auth_name 'cloudflare-dns.com'

config resolver
       option address '2606:4700:4700::1111'
       option tls_auth_name 'cloudflare-dns.com'

config resolver
       option address '2606:4700:4700::1001'
       option tls_auth_name 'cloudflare-dns.com'

config resolver
       option address '8.8.8.8'
       option tls_auth_name 'google-public-dns-a.google.com'

config resolver
       option address '8.8.4.4'
       option tls_auth_name 'google-public-dns-b.google.com'

config resolver
       option address '2001:4860:4860::8888'
       option tls_auth_name 'google-public-dns-a.google.com'

config resolver
       option address '2001:4860:4860::8844'
       option tls_auth_name 'google-public-dns-b.google.com'

config resolver
       option address '9.9.9.9'
       option tls_auth_name 'dns.quad9.net'

config resolver
       option address '149.112.112.112'
       option tls_auth_name 'dns.quad9.net'

config resolver
       option address '2620:fe::fe'
       option tls_auth_name 'dns.quad9.net'

config resolver
       option address '2620:fe::9'
       option tls_auth_name 'dns.quad9.net'

config resolver
       option address '91.239.100.100'
       option tls_auth_name 'anycast.censurfridns.dk'

config resolver
       option address '89.233.43.71'
       option tls_auth_name 'unicast.censurfridns.dk'

config resolver
       option address '2001:67c:28a4::0'
       option tls_auth_name 'anycast.censurfridns.dk'

config resolver
       option address '2a01:3a0:53:53::0'
       option tls_auth_name 'unicast.censurfridns.dk'
[/code]
3) https-dns-proxy has 3 instances:
[code]cat /etc/config/https_dns_proxy
config https_dns_proxy
#        option listen_addr '127.0.0.1'
        option listen_port '5053'
        option bootstrap_dns '8.8.8.8,8.8.4.4'
        option url_prefix 'https://dns.google.com/resolve?'
        option user 'nobody'
        option group 'nogroup'

#config https_dns_proxy
#        option listen_addr '127.0.0.1'
#        option listen_port '15053'
#        option bootstrap_dns '1.1.1.1,1.0.0.1'
#        option url_prefix 'https://cloudflare-dns.com/dns-query?ct=application/dns-json&'
#        option user 'nobody'
#        option group 'nogroup'

config https_dns_proxy
#        option listen_addr '127.0.0.1'
        option listen_port '25053'
        option bootstrap_dns '9.9.9.9,149.112.112.112'
        option url_prefix 'https://dns.quad9.net/dns-query'
        option user 'nobody'
        option group 'nogroup'

config https_dns_proxy
#        option listen_addr '127.0.0.1'
        option listen_port '35053'
        option bootstrap_dns '9.9.9.10,149.112.112.10'
        option url_prefix 'https://dns-nosec.quad9.net/dns-query'
        option user 'nobody'
        option group 'nogroup'
[/code]

4) and, at last, dnsmasq have the config using all of them with the option "--all-servers":
[code]cat /etc/config/dhcp

config dnsmasq
        option authoritative '1'
        option leasefile '/tmp/dhcp.leases'
        option localservice '1'
        option local '/lan/'
        option domain 'lan'
        option domainneeded '1'
        option quietdhcp '1'
        option rebind_protection '0'
        option filterwin2k '1'
        option dnsforwardmax '1000'
        option cachesize '10000'
        option nonegcache '1'
        option allservers '1'
        option noresolv '1'
        option localuse '1'
        option serversfile '/tmp/adb_list.overall'
        option tftp_root '/mnt'
        option enable_tftp '1'
        list server '/onion/127.0.0.1#65453'
        list server '/openwrt.org/208.67.222.222'
        list server '/pool.ntp.org/208.67.222.222'
        list server '127.0.0.1#15053'
        list server '127.0.0.1#15353'
        list server '127.0.0.1#15363'
        list server '127.0.0.1#25053'
        list server '127.0.0.1#25353'
        list server '127.0.0.1#25363'
        list server '127.0.0.1#35053'
        list server '127.0.0.1#35353'
        list server '127.0.0.1#35363'
        list server '127.0.0.1#45353'
        list server '127.0.0.1#45363'
        list server '127.0.0.1#5053'
        list server '127.0.0.1#5353'
        list server '127.0.0.1#5363'
        list server '127.0.0.1#5453'
        list server '127.0.0.1#55353'
        list server '127.0.0.1#65353'
        list server '::1#5453'
[/code].

And! Then https-dns-proxy thinks that he is most clever in the world. When it is starting via command
[code]/etc/init.d/https-dns-proxy start[/code]
it drops all my "list server", turning them into a stupid stub "list doh_backup_server" and then triumphantly adding itself as normal "list server".
This is not very good practice, isn't it? Why stubby do not change my dnsmasq config? And why dnscrypt-proxy do not change my dnsmasq config? What if I made a mistake in dnsmasq config and as a result of this mistake stubby/dnscrypt-proxy not used by anyone (by dnsmasq)? Should we say that they (stubby and dnscrypt-proxy) do not care about us? No, no and no again! Their behavior is normal.
But behavior of script /etc/init.d/https-dns-proxy is not normal. Striving for the best, nevertheless It spoils dnsmasq config.
Sorry again for my negative in previous message. Of course you don't owe me anything. But I spent some weeks was in the dark, not understanding why my dnsmasq works so bad from time to time. And suddenly it turns out that my dnsmasq have only 3 dns upstreams instead of ~30! Because https-dns-proxy imagines himself the main...

**Comment by aarond10** [comment]
Thanks for the context. Rewriting configs seems strange to me also. I'm not sure why that's happening.

I'm developing almost exclusively on arch now. @stangri has taken over the openwrt packaging. Stan, do you have any state on what's doing this?

**Comment by stangri** [comment]
@Ykidia First of all -- wrong repo, there's no OpenWrt-related code here. Second, on https_dns_proxy stop your dnsmasq config is restored. Third -- comment out the backup/restore lines of the init script for now (it stands to reason that if you've managed to create instances for 20 different resolvers in dnsmasq config, you could comment out a few lines in a shell script), in the next version I'll introduce an option for not to touch dnsmasq config.

**Comment by Ykidia** [comment]
> Second, on https_dns_proxy stop your dnsmasq config is restored
But when I restored needed lines in dnsmasq config (and restarted dnsmasq) after https-dns-proxy started, then on `/etc/init.d/https-dns-proxy stop` all the lines stupidly deleted.
> Third -- comment out the backup/restore lines of the init script
That's exactly what I had to do.
```
cat /etc/init.d/https_dns_proxy
#!/bin/sh /etc/rc.common
# Copyright 2019 Stan Grishin (stangri@melmac.net)
# shellcheck disable=SC2039

export START=80
export USE_PROCD=1

PROG=/usr/sbin/https_dns_proxy

xappend() { param="$param $1"; }

append_parm() {
        local section="$1"
        local option="$2"
        local switch="$3"
        local default="$4"
        local _loctmp
        config_get _loctmp "$section" "$option" "$default"
        [ -z "$_loctmp" ] && return 0
        xappend "$switch $_loctmp"
}

start_instance() {
        local cfg="$1" param listen_addr listen_port

        append_parm "$cfg" 'listen_addr' '-a' '127.0.0.1'
        append_parm "$cfg" 'listen_port' '-p' "$p"
        append_parm "$cfg" 'bootstrap_dns' '-b'
        append_parm "$cfg" 'url_prefix' '-r'
        append_parm "$cfg" 'user' '-u' 'nobody'
        append_parm "$cfg" 'group' '-g' 'nogroup'
        append_parm "$cfg" 'subnet_addr' '-e'
        append_parm "$cfg" 'proxy_server' '-t'

        procd_open_instance
# shellcheck disable=SC2086
        procd_set_param command ${PROG} ${param}
        procd_set_param respawn
        procd_close_instance

        config_get listen_addr "$cfg" 'listen_addr' '127.0.0.1'
        config_get listen_port "$cfg" 'listen_port' "$p"
        config_load 'dhcp'
# shellcheck disable=SC2154
#       config_foreach dnsmasq_add_doh_server 'dnsmasq' "${listen_addr}#${listen_port}"
        p="$((p+1))"
}

service_triggers() {
        procd_add_reload_trigger 'https_dns_proxy'
}

start_service() {
        local p=5053
#       dhcp_backup 'create'
        config_load 'https_dns_proxy'
        config_foreach start_instance 'https_dns_proxy'
#       if [ -z "$(uci -q get dhcp.@dnsmasq[0].server)" ]; then
#               dhcp_backup 'restore'
#       fi
#       if [ -n "$(uci -q changes dhcp)" ]; then
#               uci -q commit dhcp
#               [ -x /etc/init.d/dnsmasq ] && /etc/init.d/dnsmasq restart >/dev/null 2>&1
#       fi
}

stop_service() {
#       dhcp_backup 'restore'
        if [ -n "$(uci -q changes dhcp)" ]; then
                uci -q commit dhcp
                [ -x /etc/init.d/dnsmasq ] && /etc/init.d/dnsmasq restart >/dev/null 2>&1
        fi
}
```

**Comment by stangri** [comment]
The proposed solution is documented here: https://github.com/stangri/openwrt_packages/blob/master/https-dns-proxy/files/README.md

**Comment by aarond10** [comment]
Closing this now as it was related specifically to the openwrt packaging which @stangri has graciously taken responsibility for now.
