### ISSUE TITLE
Chroot

### ISSUE THREAD

**Issue by geekdrive** [aarond10/https_dns_proxy#74]
https_dns_proxy does not need access to any files after startup, therefore should chroot itself to an empty directory in the same manner as something like Pound (https://www.apsis.ch/pound.html) and to a certain extent darkhttpd.

While not strictly necessary, it would help mitigate any unknown vulnerabilities (along with running as a unprivileged user). I also realize that the user can do this themselves, although that requires a chroot with all the libraries in.

I don't know if this is technically possible in https_dns_proxy.

**Comment by aarond10** [comment]
I tried this just now but it's not as simple as I (and yourself) assumed so I'll have to defer to another time perhaps. One issue (at least) is that libcurl requires access to the system CA certs for validating HTTPS certificates. This is not going to be available in a trivial chroot jail unless some creative copying happens.
