### ISSUE TITLE
 libcurl bug detected: socket closed without ever being read

### ISSUE THREAD

**Issue by 0neday** [aarond10/https_dns_proxy#85]
`
[I] 1587793416.758118 main.c:160 Built Apr 25 2020 11:29:25.
[I] 1587793416.758234 main.c:161 System c-ares: 1.15.0
[I] 1587793416.758384 main.c:162 System libcurl: libcurl/7.68.0 mbedTLS/2.13.0
[I] 1587793416.759458 dns_server.c:59 Listening on 127.0.0.1:5300
[D] 1587793416.759520 logging.c:49 initializing periodic log flush timer
[I] 1587793416.760387 main.c:217 DNS polling initialized for 'dns.rubyfish.cn'
[D] 1587793416.796526 main.c:129 Received new IP '115.159.131.230'
[D] 1587793416.796583 dns_poller.c:56 DNS poll interval changed from 5 -> 120
[D] 1587793422.497687 main.c:97 Received request for id: d8a1, len: 43
[D] 1587793422.497850 https_client.c:63 Requesting HTTP/1.1: 0

[E] 1587793422.514684 https_client.c:264 libcurl bug detected: socket closed without ever being read.
[E] 1587793422.514758 https_client.c:265 Activating workaround.  PERFORMANCE WILL BE GREATLY DEGRADED!
In state 6 with no conn, bail out!
`
### ERROR INFO
**libcurl/7.68.0 with mbedTLS/2.13.0**
**ibcurl bug detected: socket closed without ever being read.**
### QA
do not support curl 7.68?

**Comment by aarond10** [comment]
That's weird. You can see where that was added (c9e74370725ee3b3fdf65ed9389ea0ea4f4d5d98). It looks like it was addressed but clearly something is still tickling it or it's a different issue. I can't don't this with OpenSSL. Will investigate when I get some more time.

**Comment by dashezup** [comment]
I got the similar error on Void Linux (musl), it crashs when I run dig to query DNS record from it, while it works fine on Void Linux (glibc).

```
$ ./https_dns_proxy -v
[E] 1595711204.820878 https_client.c:294 libcurl bug detected: socket closed without ever being read.
[E] 1595711204.820888 https_client.c:295 Activating workaround.  PERFORMANCE WILL BE GREATLY DEGRADED!
[1]    8594 segmentation fault  ./https_dns_proxy -v
```

Void Linux (x86_64-musl)
musl-1.1.24_3
libressl-3.1.3_3

Version of installed dependencies
```
c-ares-devel-1.16.1_1
libcurl-devel-7.71.1_1
libev-devel-4.33_1
gtest-devel-1.8.1_1
clang-tools-extra-10.0.0_3
```

<details>
<summary>Build log</summary>
<br>
<pre>
$ cmake .
-- clang-tidy found: /bin/clang-tidy
-- gtest found. Enabling tests.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/username/git/https_dns_proxy
$ make
[ 14%] Building C object CMakeFiles/https_dns_proxy.dir/src/dns_poller.c.o
/home/username/git/https_dns_proxy/src/dns_poller.c:29:5: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
    ev_io_init(&d->fd[fd], sock_cb, fd,
    ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/dns_poller.c:29:5: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
    ev_io_init(&d->fd[fd], sock_cb, fd,
    ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/dns_poller.c:34:5: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
    ev_io_init(&d->fd[fd], sock_cb, fd,
    ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/dns_poller.c:34:5: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
    ev_io_init(&d->fd[fd], sock_cb, fd,
    ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/dns_poller.c:105:3: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  ev_timer_init(&d->timer, timer_cb, 0, POLLER_INTVL_ERR);
  ^
/usr/include/ev.h:713:51: note: expanded from macro 'ev_timer_init'
#define ev_timer_init(ev,cb,after,repeat)    do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/dns_poller.c:105:3: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
  ev_timer_init(&d->timer, timer_cb, 0, POLLER_INTVL_ERR);
  ^
/usr/include/ev.h:713:51: note: expanded from macro 'ev_timer_init'
#define ev_timer_init(ev,cb,after,repeat)    do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
[ 28%] Building C object CMakeFiles/https_dns_proxy.dir/src/dns_server.c.o
/home/username/git/https_dns_proxy/src/dns_server.c:29:3: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  memset(&hints, 0, sizeof(struct addrinfo));
  ^
/home/username/git/https_dns_proxy/src/dns_server.c:29:3: note: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11
/home/username/git/https_dns_proxy/src/dns_server.c:53:8: warning: Although the value stored to 'res' is used in the enclosing expression, the value is never actually read from 'res' [clang-analyzer-deadcode.DeadStores]
  if ((res = bind(sock, ai->ai_addr, ai->ai_addrlen)) < 0) {
       ^
/home/username/git/https_dns_proxy/src/dns_server.c:53:8: note: Although the value stored to 'res' is used in the enclosing expression, the value is never actually read from 'res'
/home/username/git/https_dns_proxy/src/dns_server.c:89:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  memcpy(&net_tx_id, buf, sizeof(net_tx_id));
  ^
/home/username/git/https_dns_proxy/src/dns_server.c:89:3: note: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11
/home/username/git/https_dns_proxy/src/dns_server.c:102:3: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  ev_io_init(&d->watcher, watcher_cb, d->sock, EV_READ);
  ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/dns_server.c:102:3: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
  ev_io_init(&d->watcher, watcher_cb, d->sock, EV_READ);
  ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
[ 42%] Building C object CMakeFiles/https_dns_proxy.dir/src/https_client.c.o
/home/username/git/https_dns_proxy/src/https_client.c:33:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  memcpy(&(ctx->buf[ctx->buflen]), buf, size * nmemb);
  ^
/home/username/git/https_dns_proxy/src/https_client.c:33:3: note: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11
/home/username/git/https_dns_proxy/src/https_client.c:313:3: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  ev_io_init(&c->fd[sock], sock_cb, sock,
  ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/https_client.c:313:3: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
  ev_io_init(&c->fd[sock], sock_cb, sock,
  ^
/usr/include/ev.h:712:51: note: expanded from macro 'ev_io_init'
#define ev_io_init(ev,cb,fd,events)          do { ev_init ((ev), (cb)); ev_io_set ((ev),(fd),(events)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/https_client.c:324:5: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
    ev_timer_init(&c->timer, timer_cb, timeout_ms / 1000.0, 0);
    ^
/usr/include/ev.h:713:51: note: expanded from macro 'ev_timer_init'
#define ev_timer_init(ev,cb,after,repeat)    do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/https_client.c:324:5: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
    ev_timer_init(&c->timer, timer_cb, timeout_ms / 1000.0, 0);
    ^
/usr/include/ev.h:713:51: note: expanded from macro 'ev_timer_init'
#define ev_timer_init(ev,cb,after,repeat)    do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/https_client.c:335:3: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  memset(c, 0, sizeof(*c));
  ^
/home/username/git/https_dns_proxy/src/https_client.c:335:3: note: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11
[ 57%] Building C object CMakeFiles/https_dns_proxy.dir/src/logging.c.o
/home/username/git/https_dns_proxy/src/logging.c:50:3: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  ev_timer_init(&logging_timer, logging_timer_cb, 0, 10);
  ^
/usr/include/ev.h:713:51: note: expanded from macro 'ev_timer_init'
#define ev_timer_init(ev,cb,after,repeat)    do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/logging.c:50:3: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
  ev_timer_init(&logging_timer, logging_timer_cb, 0, 10);
  ^
/usr/include/ev.h:713:51: note: expanded from macro 'ev_timer_init'
#define ev_timer_init(ev,cb,after,repeat)    do { ev_init ((ev), (cb)); ev_timer_set ((ev),(after),(repeat)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
[ 71%] Building C object CMakeFiles/https_dns_proxy.dir/src/main.c.o
/home/username/git/https_dns_proxy/src/main.c:65:3: warning: Call to function 'strncpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'strncpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  strncpy(hostname, uri, end - uri);
  ^
/home/username/git/https_dns_proxy/src/main.c:65:3: note: Call to function 'strncpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'strncpy_s' in case of C11
/home/username/git/https_dns_proxy/src/main.c:112:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  memcpy(&req->raddr, addr, dns_server->addrlen);
  ^
/home/username/git/https_dns_proxy/src/main.c:112:3: note: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11
/home/username/git/https_dns_proxy/src/main.c:123:3: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  memset(buf, 0, sizeof(buf));
  ^
/home/username/git/https_dns_proxy/src/main.c:123:3: note: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11
/home/username/git/https_dns_proxy/src/main.c:125:3: warning: Call to function 'snprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'snprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  snprintf(buf, sizeof(buf) - 1, "%s:443:", hostname);
  ^
/home/username/git/https_dns_proxy/src/main.c:125:3: note: Call to function 'snprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'snprintf_s' in case of C11
/home/username/git/https_dns_proxy/src/main.c:199:3: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  ev_signal_init(&sigpipe, sigpipe_cb, SIGPIPE);
  ^
/usr/include/ev.h:715:51: note: expanded from macro 'ev_signal_init'
#define ev_signal_init(ev,cb,signum)         do { ev_init ((ev), (cb)); ev_signal_set ((ev), (signum)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/main.c:199:3: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
  ev_signal_init(&sigpipe, sigpipe_cb, SIGPIPE);
  ^
/usr/include/ev.h:715:51: note: expanded from macro 'ev_signal_init'
#define ev_signal_init(ev,cb,signum)         do { ev_init ((ev), (cb)); ev_signal_set ((ev), (signum)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/main.c:203:3: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
  ev_signal_init(&sigint, sigint_cb, SIGINT);
  ^
/usr/include/ev.h:715:51: note: expanded from macro 'ev_signal_init'
#define ev_signal_init(ev,cb,signum)         do { ev_init ((ev), (cb)); ev_signal_set ((ev), (signum)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
/home/username/git/https_dns_proxy/src/main.c:203:3: note: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11
  ev_signal_init(&sigint, sigint_cb, SIGINT);
  ^
/usr/include/ev.h:715:51: note: expanded from macro 'ev_signal_init'
#define ev_signal_init(ev,cb,signum)         do { ev_init ((ev), (cb)); ev_signal_set ((ev), (signum)); } while (0)
                                                  ^
/usr/include/ev.h:694:3: note: expanded from macro 'ev_init'
  ev_set_cb ((ev), cb_);                        \
  ^
/usr/include/ev.h:744:68: note: expanded from macro 'ev_set_cb'
# define ev_set_cb(ev,cb_)                   (ev_cb_ (ev) = (cb_), memmove (&((ev_watcher *)(ev))->cb, &ev_cb_ (ev), sizeof (ev_cb_ (ev))))
                                                                   ^
[ 85%] Building C object CMakeFiles/https_dns_proxy.dir/src/options.c.o
[100%] Linking C executable https_dns_proxy
[100%] Built target https_dns_proxy
</pre>
</details>

**Comment by SharerMax** [comment]
I have same error on openwrt, but i can't known condition for repeat it

**Comment by 0neday** [comment]
use low version libcurl 7.66 instead of  7.68+

**Comment by aarond10** [comment]
This doesn't seem an issue in recent ibcurl versions. Closing
