### ISSUE TITLE
can't make it work with Cloudflare Family resolvers (OpenWrt)

### ISSUE THREAD

**Issue by stangri** [aarond10/https_dns_proxy#86]
I've tried both `security` and `family` resolvers from https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families/setup-instructions/dns-over-https/ and:

```sh
WRT3200 in ~ # /usr/sbin/https-dns-proxy -a 127.0.0.1 -p 5063 -b 1.1.1.1,1.0.0.1 -r https://security.cloudflare-dns.com/dns-query/ -u nobody -g nogroup -4 &

WRT3200 in ~ # nslookup google.com 127.0.0.1#6053
;; connection timed out; no servers could be reached
```

Any idea why @aarond10 ?

**Comment by aarond10** [comment]
127.0.0.1#6053

https-dns-proxy -a 127.0.0.1 -p 5063


The port looks different. Is that right?

**Comment by stangri** [comment]
Oh, sorry, same result with the correct port tho:
```sh
/usr/sbin/https-dns-proxy -a 127.0.0.1 -p 5063 -b 1.1.1.1,1.0.0.1 -r https://security.cloudflare-dns.com/dns-query/ -u nobody -g nogroup -4
WRT3200 in ~ # nslookup google.fr 127.0.0.1#5063
;; connection timed out; no servers could be reached
```

**Comment by aarond10** [comment]
If you add a few -v, you get this:

[D] 1588941445.785327 https_client.c:105 CURLINFO_EFFECTIVE_URL:
https://security.cloudflare-dns.com/dns-query/
[D] 1588941445.785334 https_client.c:111 CURLINFO_REDIRECT_URL:
https://one.one.one.one/family/
[D] 1588941445.785338 https_client.c:117 CURLINFO_RESPONSE_CODE: 302

That is a webpage redirect to a marketing page. Where did you find that URL?

**Comment by stangri** [comment]
https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families/setup-instructions/dns-over-https/

**Comment by stangri** [comment]
URLs posted at cloudflare were wrong, they shouldn't have included the trailing slash, https-dns-proxy works fine as long as correct URLs are used and I'll be posting an update to the OpenWrt luci app soon.
