### ISSUE TITLE
how to config dual stack？

### ISSUE THREAD

**Issue by youxiaojie** [aarond10/https_dns_proxy#88]
how to config dual stack?
should I need to config two section, one for 127.0.0.1:5053, the other for [::1]:5053?

**Comment by baranyaib90** [comment]
Hi,
currently there's no support for that.
But you could try some tricks:

- listening on IPv6 any: '-a ::'
- or on IPv4 mapped addresses, like: '-a ::ffff:127.0.0.1'

For details see answer of: https://stackoverflow.com/questions/1618240/how-to-support-both-ipv4-and-ipv6-connections/1618259
Br,
Balázs
