### ISSUE TITLE
OpenWRT/lede issue with libcurl/openssl and libcurl/mbedtls

### ISSUE THREAD

**Issue by aarond10** [aarond10/https_dns_proxy#9]
I haven't nailed the root cause but recent builds are failing to resolve any DNS requests on OpenWRT and lede builds. Nothing appears broken about the software directly, only the binaries built from it.

CURL is reporting "Unsupported protocol" for libcurl versions built against openssl and a cryptic "no error" (but also no data) if compiled against mbedtls.

A workaround for now is to use libcurl compiled against gnutls. I notice this is falling back to HTTP/1.1 though which may push up resolve latencies a bit.

**Comment by ryzhovau** [comment]
I hope `https_dns_proxy` will be more verbose while handling libcurl responses. 

Also, may be there is a sense to handle broken system clock on embedded devices, where no RTC at all, or following deadlock may occur (as it was with `dnscrypt-proxy`):
* `https_dns_proxy` can't work while system date is incorrect, because HTTPS certs is not valid for 1970's:)
* NTP client on router or other embedded h/w can't resolve pool.ntp.org to set system data.

In this case `https_dns_proxy` just hangs with no any messages at all.

**Comment by montvid** [comment]
How do you use libcurl-gnutls in LEDE if there is no such package there? I see only the default one. Your package does not work on the current lede build any plans on fixing it? Thanks.

**Comment by montvid** [comment]
Are you going to update your package in LEDE/OpenWRT to the newest git because it is outdated and I can't use it with the current build of LEDE. You could also ask the LEDE guys to fix libcurl http 2 support.

**Comment by montvid** [comment]
I found out that for http/2 curl needs to be compiled with the option --with-nghttp2.

**Comment by daztucker** [comment]
The OpenWRT/LEDE problem is in libcurl.

On LEDE 17.01.2 with all updates, after annotating the callbacks with some logging and running it under strace I get the following debug log:

socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 6
[...]
connect(6, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("172.217.160.46")}, 16) = -1 EINPROGRESS (Operation in progress)
[..]
https_client.c:242 multi_sock_cb called, sock 6 what 2  # ie CURL_POLL_OUT
[...]
https_client.c:214 sock_cb called, fd 6 revents 2  # SSL socket gets written to
https_client.c:242 multi_sock_cb called, sock 6 what 4 # ie CURL_POLL_REMOVE

ie as soon as the socket gets written to, libcurl tells the app to stop monitoring the connection to the server and retrieve the results, which unsurprisingly are empty ("CURLINFO_RESPONSE_CODE: 0", suspiciously quick server times and a result "buflen 0").

This seems to be a known problem in libcurl <7.53.0 with mbedtls and nonblocking IO: https://github.com/curl/curl/pull/1223/commits/b993d2cca536870ecdf3b4611de9f77215af8eb8

If I build and install a libcurl with that patch then it works.  I was also able to bodge it into working with the current library by adding a call to curl_multi_perform and looping until there were no more transfers.   You could potentially detect that behaviour at runtime and enable the workaround but the performance would probably be pretty bad.

**Comment by daztucker** [comment]
Submitted https://github.com/lede-project/source/pull/1627 to get LEDE's stable libcurl fixed (HEAD is based on a version that already has the fix).

**Comment by daztucker** [comment]
LEDE pull request was closed due to the merge.  https://github.com/openwrt/openwrt/pull/674 against OpenWRT.

**Comment by daztucker** [comment]
If you happen to be using mips24kc and you trust me (which you absolutely should not) then you can try the package I built for my own use which is here: https://www.dtucker.net/tmp/libcurl_7.52.1-7_mips_24kc.ipk

**Comment by daztucker** [comment]
OpenWRT pull request against the lede-17.01 branch has been merged so if you update to libcurl_7.52.1-7 you should see https_dns_proxy start to be able to resolve addresses.

Note that you will also need to install the ca-bundle package to get the required SSL certificates, otherwise it'll continue to fail with the same symptoms...

**Comment by montvid** [comment]
Thanks for the effort. I wonder if the lede guys enabled curl http2 on by default as compiling it in is not user friendly. So far I was using dnscrypt.

**Comment by daztucker** [comment]
https://github.com/openwrt/packages/pull/5497 and https://github.com/openwrt/packages/pull/5499 to update the https_dns_package to pick up the code fixes and add a dependency on ca-bundle.

**Comment by daztucker** [comment]
openwrt package pull request has been merged on both branches, I think this issue can be closed.

**Comment by ryzhovau** [comment]
We'll merge that too during next sync.
