### ISSUE TITLE
problems with server that use cert sign by let's encrypt authority x3

### ISSUE THREAD

**Issue by AlexYe233** [aarond10/https_dns_proxy#90]
it seems that it can't work with server that use cert sign by let's encrypt authority x3,like https://ea-dns.rubyfish.cn/dns-query.
however,the command "curl -H 'accept: application/dns-json' 'https://ea-dns.rubyfish.cn/dns-query?xx' "get a correct respond.

**Comment by aarond10** [comment]
That's a bit odd because it should be using the system's cert authority list (distro dependent). Could you tell me what platform this is?

**Comment by AlexYe233** [comment]
Well it works now,and i don't know why.I just delete emty lines at the beginning of /etc/conf/https-dns-proxy I'm using openwrt 19.07.3 and https-dns-proxy 2020-04-09-3.Anyway,thx.
