### ISSUE TITLE
Provide version number

### ISSUE THREAD

**Issue by bjmi** [aarond10/https_dns_proxy#99]
It would be useful to print a version number in the Usage overview and / or provide a command line parameter (may be -V) for that
Example:
```
https-dns-proxy version 1.3
Usage: https-dns-proxy [-a <listen_addr>] [-p <listen_port>]
        [-d] [-u <user>] [-g <group>] [-b <dns_servers>]
        [-r <resolver_url>] [-e <subnet_addr>]
        [-t <proxy_server>] [-l <logfile>] -c <dscp_codepoint>
        [-x] [-v]+
[...]
  -v                     Increase logging verbosity. (INFO)
  -V                     Print version number
```
I try to find out if I am still affected by https://github.com/openwrt/packages/issues/11410 or if I already have the new build. This could be found out easily by a version number.

**Comment by baranyaib90** [comment]
I can implement some [CalVer](https://calver.org/) and [SemVer ](http://semver.org/) version combo, which is generated automatically - by CMake - at build time from HEAD git commit info.
This is something similar, than it's [already used](https://github.com/openwrt/packages/blob/openwrt-19.07/net/https-dns-proxy/Makefile#L4) in OpenWR package but with commit hash added.

So was thinking of: [2021.01.17-37511cc](https://github.com/aarond10/https_dns_proxy/commit/37511cc08712d7548978a4f6f1cc457b7594fb96)
This version string helps to easily find out:

1. how old is the software
2. what git hash has been used

and it always monotonically increases.

@aarond10 are you OK with this? If yes, I can create a pull request for this soon.

**Comment by aarond10** [comment]
Sounds great. Thanks!

**Comment by aarond10** [comment]
Thank you @baranyaib90 for implementing this! Marking this issue closed.

**Comment by baranyaib90** [comment]
You are welcome!
